package p500.srm579;

import utils.ExampleRunner;

import java.util.ArrayList;

/**
 * Created with IntelliJ IDEA.
 * User: smalex
 * Date: 5/18/13
 * Time: 8:39 PM
 */
public class UndoHistory {
  public static void main(String[] args) {
    ExampleRunner.eq(1, 18, new UndoHistory().minPresses(new String[]{"tomorrow", "topcoder"}));
    ExampleRunner.eq(2, 6, new UndoHistory().minPresses(new String[]{"a", "b"}));
    ExampleRunner.eq(3, 10, new UndoHistory().minPresses(new String[]{"a", "ab", "abac", "abacus"}));
    ExampleRunner.eq(4, 17, new UndoHistory().minPresses(new String[]{"absolutely", "abs", "absolute"}));
    ExampleRunner.eq(5, 39, new UndoHistory().minPresses(new String[]{"pyramid", "sphinx", "sphere", "python", "serpent"}));
    ExampleRunner.eq(6, 17, new UndoHistory().minPresses(new String[]{"abcde", "a", "ab", "abc", "abcd", "abcde"}));
    ExampleRunner.eq(7, 8, new UndoHistory().minPresses(new String[]{"abcde", "abcde", "abcde"}));
    ExampleRunner.eq(8, 9, new UndoHistory().minPresses(new String[]{"b", "a", "b"}));
    ExampleRunner.eq(9, 28, new UndoHistory().minPresses(new String[]{"aa", "b", "b", "bb", "aa", "b", "b", "a", "ba", "ab"}));
    ExampleRunner.eq(10, 13, new UndoHistory().minPresses(new String[]{"ba", "a", "a", "b", "ba"}));
    ExampleRunner.eq(11, 339, new UndoHistory().minPresses(new String[]{"egkteiogxpqqmxgtdlpchrtkmqtgucxalmyq", "egkteiogxpqqxstfbeallwrgfupfrmhyjjuxeqtqemorh", "egkteiogxpqqmxgtdlpchrtkmqtguckrfrnrhptswluvagvp", "egnccpdjghseesmkfwblpcaciklso", "egkteiogxpqqxstfbeallwrgffqsqsephqqlwkvfbxhtxlqwib", "egkteiogxpqqxstfbekorxnjwrymymyjgszozfztgmw", "egkteiogxpqqxstfbeallweuuubtofhxlikyyfn", "egkteiogxpqqxstfbekorjzwcnjojqojkwifm", "iauj", "exfsqtdpljdaol", "uittzzupvpyyaqrdlctuco", "uittzzupsedimmfxsxfboh", "nmchxleddqcyr", "xczoukcuvollxvyabxovwwcebwfufnmimbwi"}));
    ExampleRunner.eq(12, 202, new UndoHistory().minPresses(new String[]{"oymotipaytbqtlyxmeiufoel", "avdgjaceleuezlllxjpxxlugm", "zyzsydjiwiqhg", "quvlnbkqondhhivgxyjmlfvtonajknsyxh", "oymotbogeyvbnxiucikdwap", "quvlnbkqondhhivgxyjmlfbdcaezrbpafmatriuxgcxzftn", "pvbimvmeacititgpmobfsoncrvmwmqltkahzdhzwubjo"}));
    ExampleRunner.eq(13, 991, new UndoHistory().minPresses(new String[]{"huuvkwmy", "zxfmdmlp", "cojpdiwcmelandfyrqcednfwjz", "huuvkwmzzvyqgmqnkyfcqnvztxxtyprizctmmfla", "cojpdiwcmelandfyrqcednfwjk", "cojpdiwcmelandfyrqcedylcmbnhxeghfw", "cojusgmamwxhwziazyt", "cojpdiwcmcsygbohfbsjqqddqvegydqogrtwh", "cojusgmamwxhwzfipgtjspicmfu", "kdnotdx", "drey", "drefvwsncemrubyrgac", "rnetiastdrguhyxgvaaksfhcqnlxgvfkpff", "drcizpjnjhsvnmjggrvvpcvumkfisxd", "cojpdiwsxvdhpttbfyprstswmwhsvbgbswaypsd", "qfdkyukavsmfojuhosdnvifjnxraypvcbjvhxqxstnhncvaoj", "kdnotdxakeyhfvqjazckhfffoldgaxpohzgqpdfyx", "cojusgmamuxrbeqnnoklygepngukpnjgbpfrlectplbyda", "kvepvcoisevsfgd", "kvepvcoisevsej", "umlmnpbrdwswojrbgwrxo", "cojpdiwsxvdhpttbfyprnlslswzoaoqsvwuqllsglfrm", "uxwuvceqlsostnysyxxmhczaexpuibwm", "cojusgmavkzuopjvfhwzlzbbolkjkvnpgfwtspnojhjvsskq", "kgawkplpx", "dreasiitpehenehig", "wtjimrtwraiojbuhjzeyeopb", "dreasiitpehenehvhehmlykca", "zxfmdmlpxnsyjfmikkhenxjrlgqdassnkufjqqsfxtq", "eoiiouukhsywg", "anxhnzwcfocqmidovioajwjbaeywbnxmnyicsukljkrw", "cojusgmavkzuopjvfhwzlzbbolkjtzjayr", "cojusgmamuxrbeqnnoklygepngofddobqqeyacclaeb", "opuvujmwquca", "gscpekcoxnmmtxvbv", "dreasiitpehenehicuewmiiiyzuysurkeuejiuxcvlwxatrr", "jgegnupqlmrfcqildersgqn", "vffzkx", "qfdkyukhnoqyabusnbqlyjdppchfjwatcsiunscg", "dsupikmgumclytawjgjnxktzjwdgtdwfxbrpib", "dreasiitpehenehvhebaaxhntaxifhxxbjzt"}));
    ExampleRunner.eq(14, 670, new UndoHistory().minPresses(new String[]{"pmreerobcltzxolseyxtpxai", "nctuwdubvwtifhjbxkercwbwiplraoenkhlpsvlpywlr", "upgipwrmwzoekxnhyht", "lxplgcilptcmtsdey", "snzoplhvodxjdszysrgdtm", "snzoplhvodxuozjva", "snzoplhmqzwahshgsswiaquqonnnf", "mvg", "flqcdzljsj", "dcqjvgsbagbbttdukxnphdce", "flqcdzlyzreypamnhbfmrcvambcv", "gvmiwppgiqlxtocwvgyawpuysmshxrf", "flqcdzbbwfnsdqtasldmafpdnlwujjil", "gvmiwppgiqlxtocwvgyawpuysmsbhcmz", "nctuwdubvwtifmlfserbkxqaspbhg", "xueeuulhzzzpfbmeghoreswi", "upslatiwosnbbtsgeoihrminxfcvbdfcweznkiaedusrstcoj", "tdqfxcxuirxs", "flqxysczdnjiuewhmwoxcffjceacwqhgm", "aiiyooliknnqvbpboxbhtntyimf", "nctuwdubvwtifpmcvvuiygffpeblwhpswhkfjtdql", "axswsrv", "mvijcyntqybvngb", "nctuwdubvwtifmlfserbkxqastfkyzqgeqvqh", "lxplgcilptctcvgseoauoqaqwnmkpxau", "mozgegoaptinkqmzwpjujqcfgfsnygqvmlbsbkgbqdvllrnc", "upgipwkucjwqphyeynuogvssprqgobavwwgumuex"}));
    ExampleRunner.eq(15, 180, new UndoHistory().minPresses(new String[]{"topvtojgagzdfdmmytannzmtjzvscjivog", "vmlchzfmbpjtmlfnchafffagkxghhjdiot", "ch", "jtrvu", "vmlchzfmbpjtmlfncwoxrkwk", "wjeqaqaxnkgrscqoecyjqhrmckjpxnnc", "kghjbcscnmetlgwqdctimktsptfrwnbj", "uuofdcsy", "i"}));
    ExampleRunner.eq(16, 413, new UndoHistory().minPresses(new String[]{"qyhurldfdwcjvlxyqxblffvodpiqoscljyipwbbk", "swltq", "oxqjtesckgrhrotdnhjapuniqsafmaekrrtoqhjpygb", "xajaruacnaemxnoyz", "dpnvjzrchzlnnyoxcozufqypqpamckdnutkyuvbnyysf", "xajaruacnaehjhfxqiyxqfj", "smgjiocddukgszwpxtlhzxnvtagfiycblxmhzwuzi", "xzsyezkggzuqdrhvovzcvz", "xajaclrspfcxzvvcnwmzklkreualoahzgqfywhxejxy", "swwghvxxibnycegokhesdvncgbjetmtfggado", "swwghvxxibnycegokhesdvncgbjetmtfggatw", "dpnvjzrchzlnnyoxcozufqypqpamckoizgylxqeg", "rqhcirwpwugfolqaoejdpnnwdwpokxd", "hfxelxxlzxwurzxrj", "wiycknpglphhoy"}));
    ExampleRunner.eq(17, 472, new UndoHistory().minPresses(new String[]{"sefrquguzioqwxei", "sefrquguzioqwxetmshoxkirhgf", "sefrquguzioqwwjcvkqzpdizxcmjprouexdyul", "sefrmfmirwxswsxi", "sefrmfmpqlpmo", "sefrmfmmnastpercxdlgoorlturkdxbl", "bvwsjzm", "vbeopqqcgepzu", "sefrmfmpqlrozweakswkbsmqrhekrqxfgmmjptfghtsdghw", "dwbqauehfho", "quffvhmfshjagb", "uttcemuoivvedsr", "sentngfxlbhcrlmqwzfusv", "hxnzacpkiwaaiux", "sebntxyjijckrnzhiigitf", "sefrqusauqksbtwnlciwhlluqxkdefmhoiznyhbvg", "sefrmfmpqlrovdnksbjswzfbaexyywtnwxexudfleeulwqihfh", "sefrmyqdjfbmj", "edhmoolwovjcskifnhhowqldfjheyxbpwrszo", "vkjnqfkati", "fov", "sebntxyjijckgmefvplbygjkommmxzgldecqadssew"}));
    ExampleRunner.eq(18, 320, new UndoHistory().minPresses(new String[]{"uhmdbzqycga", "uhmdbzqycgpbhbqiiivccsdpocgednbpvwowmnfhk", "cetpzxlztveqbsiaohjotqaced", "lyifdyxxdzvhdyvpmoayjjquggrhluraclxddikxwkcroj", "dpnjhj", "cqjaeruvknvkjuakdxvgs", "vw", "dpnjvdn", "sghjcnsoidwdvo", "dpnjvxdaausbpxnkoklwhricwdkzkilta", "cqjaeruvknvkjszrtpkdzzcazrznheg", "uhmdbzqycgpbhpmhuhbylfxgwwwlymauwbkdtucjjcvlcova", "uhmdbzqycfhcafpt", "dpnjhjldxpqmbhedjyxyxaluhhgvkxfpanugazc"}));
    ExampleRunner.eq(19, 642, new UndoHistory().minPresses(new String[]{"cxmzesapg", "feofdtewlwjqkkvpbqbpjwdthvdlirj", "edzwudfsftfhhnvylmolf", "ldctq", "doc", "bqxcoctodvwtjnygunpbodaydnlvsqtaz", "adly", "swbbnqbtafxdrylo", "vtxuicexzqnloasfcxxsyiwfoj", "edh", "xwuwvwmdunzo", "vzsampeeoaiietnbcnbjuo", "d", "vtxuicexzqnloahclrsnjvsz", "njgxqxpjudspnpd", "amotateqqrpszjtzoenlbcmbjruueocedounpbrghkxnic", "rfaklzdktrmbmhpxmeofocuyvtaliujnx", "swbbnqp", "zuqxnepwnio", "edzwudfsftfhkphdlevbycnvopcoklb", "angtlnpm", "mwfcaathvaqgqwzcbcpfcmsluizxyvgmvxtfiuzbfnu", "edzwudfsftfhkphdlevbycnvopcoklhilwsfscfijmvkgspe", "excrilpzqzdw", "bzeuqulpfsbdbmagivzhbotnnccs", "lqltuwhbdmfpdnihzazeiyp", "feofdtewlwjqkkvpkdsnzgjmgntncikvsfslqwxavjfoqpkj", "swbbnqbtafx", "edzwudfsftfhkphdlevbycnvopcoklhilwsfscfijmvkgspsdn", "bqxcoctodvwxgumlevibkuosogywdjhfuymwitz", "edzwudfsftfhkphdlevbycnvopcbuofvibgmthwvv", "excrilpzqzdwizqldygezxdzjofytydyuibbpmr"}));
    ExampleRunner.eq(20, 1105, new UndoHistory().minPresses(new String[]{"slxhpnstcytzuaauphqtiskdhftaveveckpysbehqiswrdwxt", "ssfmdnspggbfofrjzfsidcxhhltenqqseh", "rogqeiz", "jjiwcbfonlmyyokqrjlgxjisjvgvkr", "pzzsqzsvbwannhjbknjqrwzspkwfmszbabul", "qhicbxuudjzonsrnzsvyibrfnjxcnxhddbdldzftapau", "pzzsqzvizyevtybhvvujwzscduwgfaouttfidpkewmifxubql", "hnntucilkahxwnshszsmkdlurwcuwrtxe", "sdnxmffryvzch", "wmyrbsqcfbubfdvtdenzezcc", "aexvmvhftkpro", "mtdeuufdfhrgxtwya", "zargbpuiuwkhkuiefelioxntmequjfaeap", "bfflzcpoginiddwxcuxiakcytpouzea", "gfwnkmtugqvhrielgekjbipwwcixbuihjwywzdpjfnfcc", "gfwnkmtugqvhrielgekjbipwwiyogmzerfhd", "jiaujbsuhwurwyovkdvcutjpagoolwciske", "jjipiugopacasudxazjimzmlshewnuncobuemn", "rdfgjllqxcjxhxndoceufyqiptzubhyhttmwvu", "svrbcadwypzoznciqyghyhhcbjcpzveqpqwguaej", "jji", "pzzsqzvizyevtybhvvujwzscduwgfaouttfiinjotavee", "ilzwyefbhcnkjclguztlyoybioqupvdtytoemaeextea", "xltxccegacrdliaumbrzrpjcsyrcobqcvnmtgbzzhlgbfihlga", "syjqlzyrkhdtnahfjqu", "komhcqrhjhchynjywxuhkdkey", "ifhutimzgjuxeeulfstqqyesbrgpotyclzeslo", "komhcqrhjhh", "up", "zjaivghvlpz", "pzzsqzvizyevtybhvvujwzscduwgfaur", "bfflzcpoginiddwxcuxiakcytpouzogtmvry", "opdxmsgmxghyjxb", "pczlestfic", "tawvqqhjynzyqtunoybd", "rdueqennroumkoffbzuvtsgkw", "ssfmdnspggbfofrjmntzreq", "hnntucilkahxwnshszsmekgwwisism", "zjegyymjdkmkreiau", "evgjpxrxmpypkzbmckvwhbugwumwxxagovcjgzipvkxfbjy", "hjiwrsxzmubdfrjyswkbwdwgvea"}));
    ExampleRunner.eq(21, 7, new UndoHistory().minPresses(new String[]{"m", "mfqby"}));
    ExampleRunner.eq(22, 23, new UndoHistory().minPresses(new String[]{"kd", "kdmsl", "kzz", "b", "khphx"}));
    ExampleRunner.eq(23, 20, new UndoHistory().minPresses(new String[]{"k", "kvcy", "imbbs", "kqc", "kqc"}));
    ExampleRunner.eq(24, 7, new UndoHistory().minPresses(new String[]{"e", "tm"}));
    ExampleRunner.eq(25, 15, new UndoHistory().minPresses(new String[]{"jvx", "d", "jmbad"}));
    ExampleRunner.eq(26, 24, new UndoHistory().minPresses(new String[]{"z", "qv", "qubie", "qvlk", "dq"}));
    ExampleRunner.eq(27, 13, new UndoHistory().minPresses(new String[]{"eirop", "eiro", "m"}));
    ExampleRunner.eq(28, 7, new UndoHistory().minPresses(new String[]{"k", "kiyns"}));
    ExampleRunner.eq(29, 5, new UndoHistory().minPresses(new String[]{"qn", "qn", "qn"}));
    ExampleRunner.eq(30, 7, new UndoHistory().minPresses(new String[]{"em", "n"}));
    ExampleRunner.eq(31, 103, new UndoHistory().minPresses(new String[]{"wyzvwvwyxwvwyvzwzzxwzwvywxxwvyzz", "wyzvwvwyxwvwyvzwzzxwzwvywxxwvyzyvvzwxvzx", "wyzvwvwyxwvwyvzwzzxwzwvywxxwvyzyvvywyxywvxvvw", "wyzvwvwyxwvwyvzwzzxwzwvywxxwvyzyvvywyyvwyxzvywyyv", "wyzvwvwyxwvwyvzwzzxwzvywyvzwxwwzyvywzyvzzwyywxy"}));
    ExampleRunner.eq(32, 158, new UndoHistory().minPresses(new String[]{"zvyxwxyzywvxyywwvxwvxzyxxyyvzxwwwyvwzwz", "zzwxxzzxxwyvvvwzxzvzxwwzyxxvyv", "zvyxwxyzyvyzvwvzx", "xzvzwzvwyvyyvyvyzyyzvzywxvvywxxzzvv", "xwyzwywzyywzxvyxvwzyyvwvyyywzvvxvxx"}));
    ExampleRunner.eq(33, 93, new UndoHistory().minPresses(new String[]{"ywyvwwwvvxyyzyyvxzxxyyvwyxwzwwwzyyyyyyz", "wzxxzwwwyxvxyyyyzyzwzywzyxxvvzw", "ywyvwwwvvxyyzyyvxzxxyyvwyxwzwwwzyyyyyyvzxwv", "ywyvwwwvvxyyzyyvxzxxyyvwyxwzwwwzyyyxzxzxywx"}));
    ExampleRunner.eq(34, 158, new UndoHistory().minPresses(new String[]{"zzzvzwzzzwxzvyzwvywzzxywyvyxvyxzxx", "zzzvzwzzzwxzvyzwvywzzxywyvyxvyxzywzwzyyzw", "yzvwxzxwyzwyzyxvyyvxwwyxywxyvyzzvzywywwwzwxyv", "xvyvvzvzzwyyzwzxzywwzvwwxyvzwwx", "wyywyyzxzwyvzyvvvxwxvzvwvz"}));
    ExampleRunner.eq(35, 102, new UndoHistory().minPresses(new String[]{"yvxvzwzzzwvvywvxvvvwyzwvyyzwwyvxxvyvwwyxzyyzvyyvz", "ywvyvvzzzwyzzvzzvyzzxywxvxvwvwxwxvvxw", "yvxvzwzzzwvvywvxvvvwyzwvyyzwwyvxxvyvwvvzxzvxvzv"}));
    ExampleRunner.eq(36, 52, new UndoHistory().minPresses(new String[]{"xvxwxxxvxyzvvxwwzyxzwxvvxwyvwywvxzzzzy", "xvxwxxxvxyzvvxwwzyxzwxvvvxxvwvxzzx"}));
    ExampleRunner.eq(37, 103, new UndoHistory().minPresses(new String[]{"wyzyzxvxzyyxwzyxxvzyxzwvzyyyywxyywzxwzxvxz", "wyzyzxvxzyyxwzyxwwyzyxwzvzvzwzzyxvwywxyw", "wyzyzxvxzyyxwzyxwvxyyyzwvzwxxxwwyzzxzwywyvwzzwy"}));
    ExampleRunner.eq(38, 35, new UndoHistory().minPresses(new String[]{"xywxxzvwwvxywzyyxzxyvyzyzvyvzvvvvx"}));
    ExampleRunner.eq(39, 69, new UndoHistory().minPresses(new String[]{"vxvywwywyvvyzzvvwzzwvxyvxvw", "yxyxxvzvxywzyvywzyxwyyvvwvzxxxzzzwwxvy"}));
    ExampleRunner.eq(40, 154, new UndoHistory().minPresses(new String[]{"yxyzvvxxyvvxwxzzzwywzzyvyxxyyzxwxyxwwzvvyxyw", "yxyzvvxxyvvxwxzzzwywzzyvyxxyywxvy", "vyyxvyyyzxywyxywzzvwyyyyvxwzwzvwwxxzywvzzzvxzvzvx", "xxzxvxxzzzvvvyvwzxwwxxyvwvvzzzxzwxvzwvzvzzvzwww"}));
    ExampleRunner.eq(41, 31, new UndoHistory().minPresses(new String[]{"bbbbbbb", "bbbb", "abbbbaa", "abab", "aaa"}));
    ExampleRunner.eq(42, 35, new UndoHistory().minPresses(new String[]{"abaaaba", "baaabaa", "baaabaa", "baabaaa", "bbbbbaa"}));
    ExampleRunner.eq(43, 30, new UndoHistory().minPresses(new String[]{"abbbabb", "abbaaaa", "abbaaa", "aabbbbb", "abbaaa"}));
    ExampleRunner.eq(44, 41, new UndoHistory().minPresses(new String[]{"baabaab", "aabaaaa", "babbaaa", "bbbabaa", "baaaaa"}));
    ExampleRunner.eq(45, 40, new UndoHistory().minPresses(new String[]{"bbbbabb", "baaaabb", "abababa", "aaa", "bbababa"}));
    ExampleRunner.eq(46, 43, new UndoHistory().minPresses(new String[]{"baaaabb", "ababbaa", "abaaaaa", "aaababa", "bbabaab"}));
    ExampleRunner.eq(47, 31, new UndoHistory().minPresses(new String[]{"baabaaa", "baabaa", "baabaa", "abbabbb", "bbabbbb"}));
    ExampleRunner.eq(48, 33, new UndoHistory().minPresses(new String[]{"abababa", "abababa", "babbbaa", "ababbb", "bbbbbab"}));
    ExampleRunner.eq(49, 27, new UndoHistory().minPresses(new String[]{"bbbabaa", "ababbba", "abbb", "abbb", "abbbbb"}));
    ExampleRunner.eq(50, 39, new UndoHistory().minPresses(new String[]{"aaaaaaa", "abbabab", "aaa", "baabbba", "bbbbabb"}));
    ExampleRunner.eq(51, 1577, new UndoHistory().minPresses(new String[]{"qspttptqtrqttqqprprqtrrpttrsspprssqtptrqrrtrsqtr", "qspttptqtrqttqqprprqtrrpttrsspprssqtptrqrrtrsqtqp", "qspttptqtrqttqqprpptssqrrpsq", "qspttptqtrqttqqprprqrttq", "qspttptqtrqttqqprprqtrrpttrsspprssqtppssqrr", "qspttptqtrqttqqprptsttrqsstrtspqpprtprrrstrpqtr", "qprsssqprrrstpqpstsprprtspqrpspqqttqrtqstssqpttsqs", "qspttptqtrqttqqpsssppptt", "qrtttsrpqrtssrqsrrsrpqpttqssqpsqrtprtrrpsrtrsrstrr", "qspttptqtrqttqqprptsttrqsstrtspqpprrq", "qspttptqtrqttqqprprqtrrpttrsspprssqtptrrrsrsrtrrsp", "rqqtpssqprtpqqqqqpppqqrrssttpptsqqqrprqtsqsrsqqp", "qpsptprqrrqtsspqqrpqtsrsrsttqtrqrqsqqsqttqqsptqt", "qspttptqtrqttrtsqprttrtqstssttstrsspprrrpttr", "pprtstppppsrrpqqtqrppsrpprsptrstqpsrqqsrsqqtrptr", "rqqrtrrprtqqrqqrpttrpqrtqqrqptrrprppptststpsspqt", "qpptpt", "qrtttsrpqrtssrqsrrsrpqpttqssqpsqrtprtrrpsrtrqtrp", "sttqsrprqtqqpprrpqqrtrqpprqrqprtqsqssrsqtrptpsppqp", "qspttptqtrqttqqprptpqqqqsstsspspqq", "pqrqprpqqrppsrsrsqttttqqqrrrssppqsttqtttsprprqtp", "qtpqqqrtrprppqrprqqqqttspttrqqrrstspstqprpstttttpp", "rqqrtrprtpqpqpprrsqqprtttqrtttppsqrrspsrptp", "ssprpqsrtrtqpptqssqptpspprrrrrrspsqsqqtrqprrpqrsss", "qspttptqtrqttqqprprqtrrpttrsspprssqtqqqqstqsqsprp", "rqqrtrprtpqpqpprrsqqprtttqrtttppsqrrssp", "qspttptqtrqttqqttrst", "qspttptsqtqqspsrrsprstqpssptprrqrt", "pqpsptqptrrtttpqptttpqprsqrsstsrprtprptppsqrptqps", "tsssrttttsrssqpqrrrrrrqrtrrpqqqrpqrrttpqpsrtrrst", "pprtstppppsrrpqqtqrppsrttrrrpststsrp", "qtpqqqrtrprppqrprqqqqrrstqsqrsssrrsrtttrq", "pprtstppppsrrpqqtqrppsrpprsptrstqpsrqqsrsqqtrptrq", "qspttptqtrqttqqprptsttrprppps", "tsqrsqtttppssstprqqsqppstpttpprrqspprsqpttprqqqt", "rqqrtrrprtpps", "qqtrtsrrqrpsqttttprsqtspqrpsqtpqrsprqrqssrqtqrrs", "tpptrpprrrpstsrrrtpqrsqsrtrrtrsrttqppsrrttrtqrqtr", "rsqtssqqsttttrprrpqpspqpqqrrtstsqstrpprpssstrtsq", "tttqpsrtrrqtptprqqsptrqqttrprqqsrqqsprpqqrrpsrpsrr", "sppqttstsrqstttqprptqpsqpptsppsprttqtssstppprrrstq", "stqqqqrsqsttrprpttpsttrssqqsqrppssrttttqrstsqpttt", "rprrtrpssrprrsptqsppqstptpqrtstpssqtsrtrpqpspsprpr", "qspttptqtrqttqqprprqtrrpttrssppsrrpqpsts", "qspttptqtrqtsrtpsstsssqqpsrpp", "rqppsrpqrtprqpppsrsttqrptppsptsrspqsqptpsrsssrptqp", "qspttptqtrqtsrtpssttrrpsqsrsrrsrsptptpqqq", "qppqtrpqqqprsttttsqrqsqtpstpqrsss", "tqqqssrrqspsssqrqrptqrsqsqsprppqpqrqqtrqpqstrrqqq"}));
    ExampleRunner.eq(52, 1500, new UndoHistory().minPresses(new String[]{"sqqsqrttpptssrsptrsrsspssppqtspttrqstpstrqprsttrt", "sqqsqrttpptssrsptrstrpr", "sqprqpqsprsspqsrrrsrqqpqt", "sqqsqrttpptssrsptrstrptrrsstptts", "qqstpsssrpqtpqtsppqqqtprrrtpsqtpqspptrrsrsrtrqsqsr", "sqqsqrttpptssrsptrsrsspsspptptqsqsrpsspqsttrp", "qprqqttqpsrtqprrsrqrqqtspqttssqqqqsrttpqssstpsrtqr", "rqrrqsqqstsqrqtsqrrqpqqsptrptrtsspqqttttspqptprp", "rpprttsqrsqptrtpqpptrqtqqspspptpqrtpqtpsqstsppqsrq", "sqqsqrttpptssrstprsssprtrstsqrqrstqqssqspptqr", "ssqsrrpqqttpqppsqtstrrqsttqqrqrsprtsspsqpsttttrs", "sqqsqrttpptssrstprsssprtrstsqrqrstqqssqqqrsppsqq", "pstpprpsqqppqsspsprrqspqsqrrqqtpqpptrsspptpppssp", "sqqsqrttpptssrstprsssprqtprpqqtrsrqtssprttqtprpsrt", "ppstqrtqsrtrqtrpttssrstssrqrrqrrqsqtrqstqtrstrqsp", "sqqsqrttp", "rqrqrqpqpstrqrrprqqqpptsrpqsrrsrpprtrtppqsttprtp", "ssqtqsptsrqrrtpqprsptqrppqsqqsrtrprptspspsqrrpppps", "sqqrsqprsssqttttqs", "sqqsqrttpptssrstprsssprtrstsqrqprsssss", "sqprqqrsrsqrtqprrqqqttqpsppspssqrqprstrrqrqs", "sqqppsrrpsqrpqsqppqqqptppq", "ttqqsqrpstqqsqsqrtptqtqptprrtrrtppspqstqrtrqqrtsr", "sqrqrpqqsptqrqqqtqqtqtssqqqtsrstqrsqrrptsqtprtpspr", "sqqsqrqrtqsrrqqsrtsstptssqqqpprstt", "sqqsqrttpptssrsptrsrsspsspptptqsqsrpstprssqsttqpqr", "qpqsrsrtsttrpsqttpqstpsqqpspsqrtqttpptttspqsptps", "qqstpsssrpqtpqtsppqqqtprrrtpsqtpqspptrrsrsrtrqsqs", "qprqqttqpsrtqprrsrqrqqtspqttssqqqqsrttp", "sqprqpqsprsspqpqqtqstrtttpsttttqqtrssqspqppq", "sqprqqrsrsqrtqprrqqs", "sqrppttsrqprsqqrsttrtqrqpqsqprsqtr", "sqqsqrttpptssrstprsssprtrstssqt", "ttqqsqrpstqqsqsqrptpppstpqqssrtqsrttqtqt", "ptqqrqpsptrpsrtrttppptprtrsqrttsssssrqtpqtrspsqstq", "sqrqrpqqsptqrqqqtqqtqqpspstttrssqrqqpqrqqprqqpr", "pstpprpsqqpsqrqsqrqtst", "srstsqqtqrpqqppppptqsrqqptttsqsssssrtstppssrsprqt", "sqqqtpqprqsqrpqprrqtrrrtsqrtqrsrst", "rpprrqpr", "sqprqqrsrsqrtqprrqqqttqpsppspssqrqprstrrqrtt", "ttptsssrssrqsqpqtpspstqpprsrtqpprpsstrtptqtsqtrts", "sqqsqrqrtqsrrqqsrtsstptssqqqpprsst", "rtprprtpsttqtrqqttrpppsqqpqprrrrqqqqsqtpststpqrt", "ttptsssrssrqsqpqtpspstqpprsrtqpprpsstrqrtrt", "sqqqtpqprqsqrpqprrqtrrrttqrsprpttrqsqp", "ssqppsqstqsrqrsrppptrssqrqqtstqpptprrsprqqpqstqrt", "ttptsssrssrqsqpqtpspsprppstpsssptpttrr", "spqrtqrrsttssprsrqqptprspqqtttpqqsrqssqqrtqssprqrt"}));
    ExampleRunner.eq(53, 1562, new UndoHistory().minPresses(new String[]{"trrpprqtstpsssqqtprtqtppqtqptttstptstrqtrpptpppptr", "trrpprqtstpsssqqtprtqtppqtqptttstptstrqtqrtssrspq", "trrpprqtstrtpptpsqttrpspqps", "pqsqqsppssrqttpqtsprrptrsprqqstppptqrrrppppqtrqpts", "tqpsqprsqsppsrttpptsqtsptqsttttqpprrrrtrrpqrsspspq", "spsptrrrprrrtsrtsrsqtssrtppqqrprtrrstpttpsqqsstrr", "tqpsqprsqsppsrttpptsqtsptqsttttqtpssprppssrtppr", "tqpsqprsqsppsrttpptsqtsptqsttttqqpspqptttrqttqtt", "ptsptpqpprppqtstssqrrrtstspqrqssqptpssqsrqqstqqrtr", "rpqsstpsssqspptspqrqsssqssqprtsrqtqtsrrqqstqsttpr", "rrqtqprpsrqtqqrtsqpptstqtsttprqtppqssqrpqppqpqqtsr", "rrstptsttptrspqqsttpqqsstqsqsqrtptspqstrqqtprqtqp", "rrstptsttptrtttpqqtqqstsrpsqpprqsrtsqqttr", "qqssssppsrrtpqrprpsqqqppttqqtqrqqqpsqrsqtqrqqtqtrr", "pqsqqsppssrqttpqtsprrpttrtpqrprqrtrsppsqttsst", "qqssssppsrrtrttpst", "pqqrqqqtpqtrrsppprprrtrtpqtrstrtpptsrpptqssqttrqq", "trrpprqtstrr", "pqsqqsppssrqttpqtsprrpttrtpqrprqtttqpppqprtp", "qttqsqpspsstrrsrtstsqqsrstqssptqstqsrtrpqppssrqtrs", "rrstptsttptrspqqsttpqqssqqtt", "tqpsqprsqsppsrttpptsqtsptqsttp", "trpqptrrssspssprsqqtttpstrppppsqprtttrspsprqsrtrst", "tqpsqprsqsppsrttp", "sppsqsppqrtqstpsqpqpqssprtrqrqttpqqtrqtprqttqsqrr", "trrpprrtrtqpprt", "ttpprrtssqtsqqtrqttpppqrrrttsqqqqrqqssssppqttrrp", "qprtptsspppptpstrrqqsssrsrqrtqttqsqpttsrqpqqtrtrpr", "rrstptsttptrtttpqqtqqstsrpsqrppqsrqprsprpstpsrsr", "tqpsqprsqsppsrttpqtppsrpqrrrs", "pqrpprsptprqrsptptsqsqqtqrprtssqprpspsptrrprqqpss", "pspprrtrsppsqrqqptrttpqptprprtspqrqtpsppsppsrtqr", "tqpsqprsqsppsrttpptsqtsptqsttttqpprrpq", "rqpqqsqqqsqrsrstrsssqqpqqqptpqtqspsprtptpsqpqsqt", "pqsqqsppssrqttpqtst", "qqssssppsrrtpqrprpsqqqppttqqtqrqqqpsqrsqtqrqqtqtrr", "qprtptsspppptpstrrqqsppqqptpprtsssrp", "qrpssppppsrrsprrrrppqqsqtpttsprtptttrppqspqptrptst", "prrqtspqstprsqrprppqrrpqtsqqqpqstpqrsrqrrqqqsttppt", "qqrrprstsqstsqsrtrqrqrrtrtrrpqptrppssstqssstrtqp", "spsptrrrprrrtsrtsrsqtssrtppqqrprtrrstptrr", "qpqrqsttrstpsrppprrrqssprqrqsqspprrrrstttspsppqs", "rpssqsppstrqqtrqtqqtqrqqpqrqrsrtssqsqpsqqrqsqrprqt", "tqpsqprsqsppsrttpptsqtsptqsttttqpprrpptrqqp", "qtttpprpqrqqrsqsqprssqssptrpptstrqstssprtrprpqprsq", "trrpprqtstrtpptpsqtssstprrqr", "rpqsstpsssqspptspqrqsssqssqprttrr", "psppr", "rrstptsttptrs", "qqptsrpqtpqssrsqqsssrsrstprspsrpprtpttqrprqqspqprt"}));
    ExampleRunner.eq(54, 1660, new UndoHistory().minPresses(new String[]{"sqtsqrrssqttstqstpttqrtttpqqqqqrqqprtpprpsptqtsrsr", "rsrtstpssqststrpptrqrrrpsqspprrttttpqsqspssqqprq", "rsrqrpqttstqqtprsqpr", "srqsspqtrsqtrqqttqsrtptqtprssqrqtstpsrptsqptttprrp", "srqsspqtrsqtrqqttqsrtptqtprssqqrpqqtsrprsstrr", "ppsqrtsrtqsqsrssqtqttrpqtsrtqqtttssqrpptsprprtqqp", "sqtsqrrssqttstqstpttqrtttpqqqqqrqqprtpprpspt", "ptsqpqtppqprrtpsqrtppqpppqqptttprprtpqpspqtprsts", "ptsqpqtppqprrtpsqrtppqpprrpptqprprpprtss", "rpqptsrqsspqtsrs", "qrtqspstqqqqqqsppqpssstrqpqsttqqsspppqrtsqttpsrsq", "rtsrprtqprqprqsrttsssqstrpsqrtrstqpqqrsssqsttprqpp", "qrtqsqstrtrttqrpptsrr", "rtpptsqpsqqtrqpstsrqqrsrptrtsrtssqtrrtqqsptqpqsts", "pprpqtqqsqqtqrpprpqptpqpprrsqrtppqrssqpqsqssrpsq", "sqtsqrrssqttstqstpttqrtttpqqqqqrqqprtpprpstrtq", "sqtsqrrssqttstqstpttqrtttrqssrsqsqqqrtqt", "pprpqtqqsqqtqrpprpqptpqpprrsqrtppqrssqpqsqssrpsrs", "rrpqtqstspqqprrpppqsssspqsqqtqrqtpprqtsrtqprrrtsp", "rtssstpptrpqqttrqsttsrstqqtsrrtptqttssrrqrqsqqpt", "qtssrptsstrprssrptrtrqtpqpsptqsqqrpsqrrttptspqqs", "qqqqqqtqsttrpprtqqpprrsrrpqtrsqtqstrpprrtprrqpqr", "rtssstpptrpqqttrqsttsrstqqtsrrtptqttssrrqrqqsr", "qrtqspstqqqqqqsppqpssstqrqqppqq", "sptqpqstrppsstrprprtpssstrtpqqtttrpqqstpprtqtppr", "qqqqqqtqsttrpprrrqqrspttssptptpsqtrsrsrrpqrqqsrrr", "rqqrttppsttrrrtrqtrsqsqsssrprssqtsqpqsrsqtpsspqst", "rsrqrpqttsqqr", "prtpqttsqrsssqqrpprrqppprsqptspqpqqrtqppsttssttsq", "sprtrsprpptrsqqrtrrqrqpssstpstpsrrpptqtrprsrppqtq", "qtqsssprqttptrttpssrtssrsqptsqsqqtrppttptssttqrrqq", "ssttrttspppsrpttrrpqqrtrqsqrpsttpptspqrrqqpprrqsq", "qrtqspstqqqqqqsppqpssstqrqqsqq", "qtssrptsstrprssrptrtrqtpqpsptqsqqrpsqrrttptsr", "sqtpsptsqqqttqttqrqppqstpqtrrrsstrtrtr", "ssttrttspppsrpttqqprtqrtqq", "qrtqspstqqqqqqspsstpsqrqtsstqtttsqsqqsrtststrpqtsr", "qtqsrtstttqttstppprqqrptptrtsprsqprqprrrsrssqstpt", "sqqsrsrssstqqrstqpqqpptsspqqtpsqqprqsrsqqstqrpppqr", "qqqqqqtqsttrpprtqqpprqsqrtqpsqsrr", "sqtsqrrssqttstqstpttqrtttpqqqqqtrsss", "qtrrpttppq", "tssrssrtstqtqrsptpqttspqqtprqrqqpqsptssqpprrpqrq", "rpssqqsqpstssprssrrpqqqrppsqrptqrrpqqspqqrppqptp", "rpqptsrqtsqsrpqstsprqppqpsqrtsrtssttqst", "rtsssttsqqsqtsptqptrpr", "ssrsrsrppqprrqpsqsqsqrrtpqtppsrrttstrrtrqtstpsqtr", "tpqqtprstttprqpsttspttsrqpqpqqqrqrtpqqtqsttrqtqtqs", "srqsptppqtppqppspprqrsrsss"}));
    ExampleRunner.eq(55, 1559, new UndoHistory().minPresses(new String[]{"qstrpsrqrrrqqpqppstqprtpqrrsrtrrqpptttqtqsqtrspp", "qptpqrpqrstrrsstprpqtpqrssqqrsstptpppspppqrqqtqpq", "tpsqtqqqtrrrspsprsqqsqttsqrqpspstsrrrpprqqstpprttr", "tpsqtqqqtrrrssrrstpttqsptspppptrrrtpqptqpstsr", "tpsqtqqqtrrrspsprsqqsqttsqrqpspstsrrrpprtrtrqs", "qspqqrspstprrqqtpptqrrpqsrqrrtqrtsrrppppsqsrqpqtqr", "tpsqtqqqtrrrssrrstpttqrpqppssrsrr", "qpqtrrrtptrpppttpqsqsrttsrsqrrtqtptsrqsrtprqtqpsr", "tpsqtqqqtrrrssrrstpttqsptspppptrrrtpqptqpsttqpqs", "tpsqtqqqtrrrssrttrssssqtqrprqrqpqrtt", "tpsqtqqqtrrrssrttrssssqtqrprq", "qstrpsrqrrrqqpqppstqprtpqrrsrt", "tpsqtqqqtrrrssrrstpttqsptspppptrrrtpqptqpsttqpqqtt", "qspqqrspstprrqqtpptq", "qpqtrrrtptrpppttpqsqsrttsrsqrrtqtptsrqsrtprqsqspt", "sqsrrrqtrrpprqstqqstrtpqrrtqtpssqtpqpttptprrrrtpps", "qrspsprpqsqpqtrtptsqtrqqstrrpsppptsrsrqsrtpttrts", "tpsqtqqqtrrrssrrstpttqsptsppppq", "qqpsrpppqqrrpptqqtsssqsrpqtpppsrqtppstpqttqrrqtspt", "rtqtspprqppppsqsprtrspqspppqrtsrtqsqrqtrqqrprstrs", "sqsrrrqtrrpprqstqqstrtpqrrtqtpssqtrsqpstspqr", "ptssrptpprrqstqptsrqrtrtptprpqsqrprpptprtrtqqpsss", "qsprqqqrrqrpqqpqsqtqttpstrtsqtptpttttqrtrprsqtstp", "tpsqtqqqtrrrspsprsqqsqttsqrqpspstsrrrpts", "qsttttqtsstpqqtpstrpttrr", "rtqtspprqppppsqsprtrspqspppqrtsrtqsrppprpqs", "tpsqtqqqtrrrspsprsqqsqttsqrstqrsptstsrqrtstpsspsr", "qstrpsrqrrrqqpqppstqprtpqtqrrqttttpsrrptspsp", "qqqssppqrtspsstprptpsrqpqttrtssqqstrrpqptstsqrprt", "qspqqrspsrqsrpptqstrqtqrsptqpt", "tqpspqqpqqrtqsqqpspspsstrtqrqrprtpqpspsttpttrqpqr", "pqtssptprsssrqtrqttssrssrqqqqtrprptpptqrtqtqstpsrt", "rsrpqpqptptpqsrpqstppprtpqtrrpsrrsqsqqpspstqspqrqq", "rsrprsttqqrtsrrqttpqttqssrsssqrrtqsstrpsptsqtpqrqt", "rrtpqpqprpppppstsqqttprqrqpttprtspqrtqqqsssqqrpptp", "psrttrsrstpqqprtppsprprpstsppqsstsqprppqpqpttqqtp", "pqqrsrprqrpsqrprqrrqrrstrprptpsttsqqtttprrstttsqs", "pqttqqqspptrstqspsqqsptqprtprtqptptqq", "srrprspsqqsttptppqprsqtspsqsqtqqsqqqstqsprpptsrs", "qsprqqqrrqrpqqpqsqtsssptrsssqstsptsrtr", "qspqqrspstprrqqtpptqrrpqsrqrrtqrtsrrppppsqsrqpsrrp", "rtqtspprqppppsqsprtrspqspppqrtsrtqsqttp", "tpsqtqqqtrrrspsprsqqsqttsqrqpspstsrqqtsqtqqqqrs", "stqqspsrtstqsqrtspqprpqsqtqtpsqssrsstqqrqsssspqss", "rrrpqrptrpttsqrrrqrrtrtqprrpppptsrrtrrprrtssqpsptp", "ppqrqsppttpsqssptstsqrtprtqsrttptqpqrststqrqqprqpp", "tpsqprprqsrqqrrrrtrtqqtqtrqsrprptsrtpp", "psrttrsrstpqqprtpptprpprpsrpsqqprprr"}));
    ExampleRunner.eq(56, 1723, new UndoHistory().minPresses(new String[]{"qsprstqpqttptrrtptqrsqsqrtrsrqqrqtqrttrppsrtpsqptt", "spqqrsqqtspqpsqrtpqttqsqpssrqtqqqsspssstprpqsrpp", "ttptttqstrtrtrrqsrrrssrpsqqrqqptqtspstpqstrprqqsst", "qsprstqpqttptrrtptqrsqsqrtrsrqqt", "rprqtttppqpttsrrpqqspppprprptrtsqrtttrqptrtpststsp", "rpprsrprprrttsrtqtrqpsttqqqrqtprrspqqqqtsttsrsqqqq", "rpprsrprprrttsrtqtrqpsttqqqrqtprrspqqt", "spqqrsqqtspqpqr", "ttptttqstrtrtrrqsrrrssrpsqqrqqptqsrqpqss", "spqqrsqqtspqpsqrtpqttqsqpssrqtqqqsspssssptqstq", "pqspqrtrtrstsstsrrssqqrsrtpptpssprpppqqtqrpqsttrpr", "tsprssqqpqtsttpstsrsqprqsppqrssrtssrptprtpptqsssr", "spqqrsqqtspqpsqrtpqtt", "qsprstqpqttptrrtptqrsqsqrtrsqqptspqrssrsstsqspstrs", "spqqrsqqtspqpsqrtpqrrptttpqrqrtqtqrqsprsrrrtrpqr", "qsrrsqqttprsqqqttpqrqpstqtprprtpsrtsptqttsrqptqqp", "ttptttqstrtrtrrqsrrrrrrprrrppsrrttsqrrprqtstq", "qssrq", "sqqrpsqrqrsrsspsrtpqqrrprsqqpspqtrpqsttqtrrsptsrqq", "prsqrqtqrsqrrrqsqsqttsprsqqtsppptstrtprtqttprpsrt", "tsssspqtrttsttpstpqtttqtrqptrtqr", "rqtppqtrsrpsrqrpsstprttrpqqtpsqrtqtsrpqsppprsqrr", "ttptttqstrtrtrrqsrrrssrpsqqrqqptqtspsqqpssqrstss", "trtsqpsrtttrprptsqrsqrsttpsqstrpsprtstssrrptpqrss", "rpprsrprprrttsrqsptrqpsstsrqpqrrrs", "ttqsrqsrspprqsrtpttptsppsrtrtrqrrttrrtqrqssrpqsrt", "spqqrsqqtspqpsqrtpqppsrrrrts", "sqsrqrpqqrssrtpttpqppppptstssqqptrrrsrqptsprqsqqq", "rrptsqqqqtpppqtttsprrsqqtptqrssqrqqrppsrtqrtqqqtq", "tsprssqqpqtsrtqsspqtppstrttqqrrprqq", "qsrrsqqttprsqqqttpqrpr", "spqqrrsttrtspq", "pqspqrtrtrstsqptsrppsssqtqsqqtspr", "tsssrrqrtqqrqstqstpssspsrstpsrsqpstptspqtqqttqrtp", "ppssqppttpstqtqttrqsrptppstttpppptpptrppsrpsspqps", "trsqpqrqtppspqsrtpqrrtsqpsrpptsqrrrrpqtrrstpqstrts", "spqqrsqqtspqpsqrtpqrrptttpqrqrtqtqrqsprstpsprs", "prtqptqssppqrtspqsrtrtqpqtrstrsrrssqtqrrsrspqssrs", "rptppsspsrrqrrqtqqptpspqqpttrspqtrssrrsspqsssrsq", "rrqqtrrqstsqqpstssspqqqttprqqrststrrsttprpspprst", "stqtspppqpprsrtrpqsrtptpsrssrptrpqstrpsspqpsqprqs", "ppsqsssststsqssrttqtprtpsppssrqtprstpsqstssstpqr", "psqtpptqssprprsrppqsstqstptprtrqtrpptqrtqspssrpq", "prsqrqtqrsqrrqsrttqpstrqqpqpqpqst", "tqtqspprqptsptpqtpqtrrqtprsrrsrpqsqrqrqtqptttqtq", "trsptqqsrqtsrtprtpqtrtptpqqqqqqqrspsqsqsqpttttpssq", "pqsrpttsrrpprrprqtqqstrptttqqspqtrtprrpqqstpsrttrr", "rsqprqrpsqpttprtpttrtrqqsstsspstqqrpprqtttsppptsrq"}));
    ExampleRunner.eq(57, 1763, new UndoHistory().minPresses(new String[]{"qtrtsqtpprpssrtsrqtqsssstsqrqsppprpttsqrtrptsrsrrr", "ptsrqqsttpsqqstrrsprqtqqttsqqsspstqptppqsrtqrsrt", "qqptsrtqtrtprrprrrtqptrsrrtsrtrtrtqtttsrtrrqrpqprq", "rttsrpsrtrsrrpqtpqqstrspqpstpptrtqstqqsqrqrqptrts", "ptsrqqsttpsqqsttptqsqqs", "rttsrpsrtrsrrpqtpqqstrspqpstpptrstqsprtrsqqqs", "qspssrspsptttpsrqttqspstqrsppqstsptpttrtqqqtptsqq", "rttsqpqssqrtpqrtpsrsqpsssqpsr", "ptsrqqsttpsqqsttqstr", "ptsrqqsttpsqqstrrtssrppspspqrqsrqpqqtrspqspppqqs", "rtspstpsqpsrqqqsrstprssttrpsrqptrssqtrtprpspqqrsrp", "rttsrpsrtrsrpsqrttqrtrrqqqsr", "ptpppspsrrsqttqstrsqqtpqrptpttqprpptsprtppqttrsp", "rttsrpsrtrpqppptsrpqpqrpp", "rtsrqrssqrpstrtqtspssstrqppqtprpssrstsrrsqsrqqpt", "rtspstpsqpsrqqqsrstrsrqrsqptsrsttssstpts", "qqptsrtqtrtprrprrrtqptrsrrrqprrpqstrsqrtptrqpttrt", "rrsppsrttqqttptqstqqrsstpqpqtqqtqptqrttqstrpqsqr", "strrtprrpqsqtqtrtsrpqrprsrptrstqpqttssrptpprtprrr", "rspppprpttqtpstqspprsrqsrsqrpssttpqpqptqrpqpsppptt", "rtsrqrssqrpstrtqtspssstrqppqtprpssrstsrrsprrp", "rttsqpqssqrtpqrtpsrsqpsssqpsrsrtprtqsr", "rtqtstqptrrprtpqqpsstrqpprqrqspqpsqpptprtqsspqprq", "rrsppsrttqqttptqstqqrsstpqpqtqqtqptqrttqstrtsrprs", "qtstqqtspqstrptrptsqrsqtprtsqqqpttpppqqrsqtprsqqt", "rspqrqpqrrprqqqrqptrqpqsrrrsqrtqrsqtqtrqpsqqptqsrr", "rtspstpsqpsrqqqsrstprsqrrrrptsqqrqstrtsrqrpqppqsqr", "tpppsrqqqsptqtpsqstpsqpsrrtsrqpttrsssprrttsssqtpqq", "ptssspsrtqptqqrstqtrsptqttppqrpqptrrqsqprqrqrsps", "qtrtsqtppptrs", "qspptqqrrtsrtrpsstspqrpptpqpsrsrpprptrrtsqrpprrtr", "qrptprqpqqrsppqtstrtqsprqqssprpsrqrtsqtppsqrtpsrqt", "spprqrtqtqrtsrpqqrtqrtsssppqqsrrttqqttsptqprsrsqq", "srqtqrsrpsrqttprsqtqqqtqsqrtttrtrpqttrptpptsqrsq", "tsssqqsqqsprqqrsqpqrsqqqrpssprttpttpprqqqrprpppqp", "rrsppsrttqqttptqstqrppqrrtqtqpqrs", "srqtsspqrssqqqqttqpsptsrssprssrpsqtstrpspprqqspt", "rttsqpqssqrtpqrtpsrsqpsssqpsrqtpsqp", "rspppprpttqtpstqsppqsqppsprqpptptrtssst", "ssqtrqrsrprrqqqqrttrqrppprpqrrrqpstqrpspstptrtspt", "rsqqpqttprsrrrrpqrsqsrpqtrpprrqpprqttttppqtqqprs", "qrprpqsrqqrtqttsssstpqssrqrspstqstpqsttrsprpqqsr", "rtspstpsqpsrqqqtttprpqpt", "trpstsprsttrqqrtpppqpppqqstrtsqttqqqrstrtpqtsqrtqt", "rsqtqsspqrtptsqpttsrpqppqqqtrtqrsqtsstptrqqtrrqp", "rsqqpqttprsrrrrprstptqtsrsspqqtqsrqs", "spqpqrsrqtqsttpttqppsrqssssrpqrrrsrqrqsssrprpsttrp", "tsssqqsqqsprqqrsqpqrsqqqrpssprttpttpprqqqst", "tsssqqsqqsprqqqqstsqppqsppr"}));
    ExampleRunner.eq(58, 1946, new UndoHistory().minPresses(new String[]{"psrtrprtssprpqsqrsqpptsrrqptqqptpqttpptstsrrrpsrt", "psrtrprtssprpqsqrsqpptsrrqptpsrpprsrtqqtqpprpprst", "ttpprqssspqptqtrrptqsttpsqrrpsspqtppqtrpspqtrttsr", "psrtrprtssprpqsqrsqpptsrrqrpq", "psrtrprtssprpqsqrsqpptsrrqqsqrpqqprsqqrrtqsrqrps", "trsstspqrpsprrsqrtstqttsqrtrsrrtsssrprpsrsrptrsrq", "qttppsstsqpqpsppstqprsptrtptsrtprqspsprqpqqptstrt", "trqrstppsttqptrttpqtrqstqqqqrttppqtqspqtrpqrrrqqq", "tqqsrqpptssqtttptrsqtsqqtrqprqrrsprsspssqppqqtpppp", "qprrsrrqrrqqttpppttsptptptpstpstqqqsrqttqqrttrrrpp", "psrtrprtssprpqpprppqtrrsttrttqtppptps", "ttpprqssspqptqqqr", "qqpptqqqrtpttqprsrrqsrqrrrqrspqsrpqptspstttsrspstq", "stqrspstsqpqsstrrsssspsqqrrqrsrtrqtpprrrsrtqtprsp", "qprrsrrqrrqqttpppttsptprqrrtsptsrprt", "qrppqtqttrttrpqsprrqrsptstrsprqqsqssqrrstrtsrtpt", "ttrsqtqtqrrrrrpqtqsstsrrqqsqprrtppqrqstspsqpqppq", "qttppsstsqpqpsppstqprsptrtptsrtprqspsprqpqqptstsr", "psrtsptrtspprqqpsr", "sqsppstrqrtqrqrstprrqttrrtppqtpprpqssstqrqrtsqqs", "sqtqssqqprrqqtspsqprpttprpttsrpttrstqpqtsqrrrtrpt", "tprstttqsqstprpttrpqrttsqttqrtppqtqtrstrqppsqrptq", "qsttrprtpqstrqrqssqtqqsssrssstqrssrqtsrstqqpttqsqt", "rsrssqqqrqprqqtpsptqqtqssttqsqqrpqtqtqqsttsssrrrst", "tsrprsttsqsqspqstrtqqqsptpstttqpppptspqtpqpttqqr", "ssssqtprsrtpssqsprppqtprpprtrrtptrqrtrrpsqqpqqprsq", "trtrrsstrqpqrrtrsrptsptpppssqrsspqstqtttrpssprttrq", "qtppsptptppqrptpsqtspqttrqttrprqqptstqtsrssqprqs", "qpttpqqppstststqtqsp", "qpttpqqppststrqttqpptpqsq", "qsstqsrqptsprprpppssppptprpsqqrsstrpspqpqstsqrtqr", "trsstspqrpsprrsqrtstqttsqrtsqqrtrprsqssrsqrsstt", "qttqrqtqtsttrptrqtrqpsqrqtrsqtsstptsttptsstqtsrs", "pprrssrrrtqprqsprtrqttssqtqqtprqsppptstprqrstqrqsr", "ttpprqssspqptqtrrptqsttpsqrrpsspqtppqtrpspqtprt", "pptssrqsrrtqsqtsqssrrqqqstpppttstttrpprprqqtppst", "qpqpqrtttpspsrrrttsppspttssrtqrqrppsqqqttrqqpqtppp", "pptssrqsrpptrqptpp", "qpqqssqrttrptqqpttqqqprtrprtrsprtrsrttptrprpstps", "ttppsstsrtqsqqsqspqr", "srqtsssqtqttqrtrrstptrrqqrqqrsrsqttptqsprrpqrqtptq", "rpsqstqtrpsppsssppsppsttqpqqqtsqrrqrtsrqsstqtqtpp", "ptrtptsqpsssstrptttttqqrqrstpqrtptrqspqstpqprrrss", "psprsrrtsprsstpsprrssrssprtqspstpssrsqrtrtpqttssrq", "tprprssttptpsrssqprrrtsspsrrpsssqptpqsrpsqtsprpp", "ptttsrstrptsrtsppqqrspssspssrrtqqsqqrsqttttsqtss", "rppptrrqtsstrpqrptrprsqsprrtstrtptrtqtrtrqttpsrrrt", "qtppsptptppqrptpsqtspqttrqtsqpqsrpts", "tqqsrqpprsptspqrprpt", "qsstqsrqptsprprqtttrqsqsrttqsqsqqrtptqs"}));
    ExampleRunner.eq(59, 1578, new UndoHistory().minPresses(new String[]{"qtqptttrrrsqprpsrsttsssrtqspsqttstprpssrrsqprtttqq", "pprtsrssrspsptppssrttsqqssrpqqtsrspqtrqtrstqttqq", "pprtsqttspppspqrqr", "qqrspppptqstqstspttrpqsptqtqtpppqpsqqtrstpspttrtpr", "tpsstrqrrtqprrrpqrsttrpqqtqtrptsrsssppttrttqsrsqsp", "pprtsrssrspsptppssrttsqqssrpqqtsrspqqqqqpspsq", "pprtsrqttptsstrqtsttsrtrspsqsqprtsrt", "rrrtrqrrttsrptptrqqrqtppsprsqrrrsrsqsrpqptsqstsp", "pprtsrsqtspqsq", "qqrspppptqstqstspttrpqsptqtqtpppqpsqqtrstpsptr", "pprtsrssrspsptppssrttsqqsssrppsspstrptrqqpsqqqt", "pptrsqsqqrtptqqqpqrpttqpsrrptssrtpqqsr", "tqrqsqrtspptqtpssprtttpptqtsrtqtpttqrsrpttprssqr", "pprtsrsqtspqprrsqrrrrsrqrrtrrrsssstrqsqrtrtttqsrtr", "pprtsrssrspsptppssrttsqqssrpqqtsrspqrqprtrpsqprr", "qrrstqqprrssppsqrtpqqtqrqsqqtsrrrstqsqpsrqptpprtpp", "pptrsqsqrspqtrsqqqtpsqqsrsrppstrqpsstsrpqtq", "qqrspstrrrqtttrtsqr", "tqqqqpsprtpspqsrrptqstsppspqqpsttttqpppttpqprptts", "pprspqsrtsrsptqpqrtstqtpqrrqsrtqqptprssrtrrqsrqq", "ssqqrstqsqsptssptsqpspttrqsqrrttspqrqqtpprsqqsrqp", "pptrsqsqrspqtrsqqqtpsqqsrsrppstrqpsstsrpqtqq", "qqrspppptqstqstsrqqstqtqstsssrsqpsqppssrsqsrprqr", "ptrrprsqtsptssrtrqprppqrptsrttrsrrstptqpqqtqttqtq", "pprtsrssrspsqqprsprpqrtrrrqtsqq", "pprtsrssrspsptppssrttsqqssrpqpppqpqtpqrtsqq", "ppqprrprpqsrqqrrsqrpprrsqtqrqptrqqpqpprqsspsp", "rrrtrqrrttsrptptrqqrqtqppqtqs", "pprtsrssrspsptppssrttsqqsssrpqpqs", "qrrqrppttqttssrqttpprrstttpqrrsqprprpprrpspstsrr", "tsqrspqstqspqprpprtstqtrqppqsppqtqqqpsttqspsqqrtp", "qqrspppptqstqstsrqqstqtqstssqspqrtqtqtsqsqptqrttq", "ttsqtrqtsqpsrspqsqrpstppsssqsqsptppppptptptstsrs", "tptptpqqqtrspqrppqqssrsrtrtqsprpspqsrrsqtqssprtqr", "ppqprrprpqsrqqrrsqrpprrsqtqrqptrqqpqpprqsspsptqrp", "ppqssqqqpqrttqrrsqqsqrrsqqpsstrqqpsqttpssrtrqpqtt", "tqtptptrsqtstqrrptqqqqsqsqssrsp", "rrrtrqrrttsstt", "pprtsrssrspsptppssrttsqqqpspsqqssprpp", "trsqtqrrspqpspqtttspptpqsqrp", "srtttpppsrqptqspttrtrsqrrrprqsqrpssrstrprrrpqqqs", "pprtsrssrspsptppssrttsqqssrpqsstsqrqpqrpprtqrt", "trsqsqtqrqrqsrtsqqtrrtrsr", "pptrssrqqqpqtsttsrsspssqprsqqprppqppptpprtpqrsrttq", "rrrtpqprrtqssrssstrstptrqpssrpsqrqpqssqpttrsrptttq", "pprtsrssrspsptppssrttsqqsqrprqrpsqt", "tptptpqqqtrspqrppqqsppsrp", "rprrqtqrrqpptsrqpqsssptpprrstpqtrsttprrqtrtqsqprqq"}));
    ExampleRunner.eq(60, 1690, new UndoHistory().minPresses(new String[]{"pqqqpttspstpsssssttqtpsprtspttqppqqpqrsspqrpssrsts", "pqqqpttspstpssqstrtsqsrrrsrprrrsqp", "qptprtrpqsqqrqpssqsssprrsqprtpprrqtsstpsrqttqrprpt", "qptprtrpqsqqrqpssqsssprrsqprtpprrqtsst", "pqqqpttsppsrtptttqt", "qrssppsptspsqsqtpsprqsttrprsrqqqrtrqtqtqrtsstrprr", "rqptpspprpsrqsptqtsrtsssppqpsqrppqtrtrpqtrstqrrp", "ssqtprtpqtpprtpsrspprqsrqqrqpsqpqrsptsqqqqqstprsr", "qptprtrpqstsptsrtpssqq", "qptprtrpqstsptsrtsqrsqqrtqqsrqpqssqprqrqpptqt", "rrrtrtrrqqppptptqtprtrrrprqtrrtrppqrqpsqrssrqrsqq", "rqptpspprpsrqsqspqsq", "qptprtrrstrpqrqppqpsptspsprs", "pqqqpttstqqsqrptprqqrtqsrpsspsssq", "qptprtrrqrpps", "tqtstqrrppqrrptrrptpqrttrrqrsqrtqsrqqqrprspqrtqt", "rqptpspprpsrqsptqtsrtsssppqpsqrppqtrtrpqtrst", "prrrstsrrpsqttpqtqrtppsrppqppsttqqrttsrstpprssqs", "qptprqrqpttqrsprrpqrtstq", "pqqqpttsppsrtptttsrqtsptrqppqstrtppqssprqtpts", "pttqrqsqqsrqtqssqpsrppprpppsqrrprrqrrtrttqqttttqsp", "rqqprspqstqrqqrqptpsppttqqqtpspqrsqpstsqpppppstssp", "qpsqtsstqqrqqpqr", "pqqqrs", "qqqprqprtstrstrqsqtssssssprprrtppqrqssrsrstrqpsqsq", "qsqtptqrqptrtqtssqqprsqpqrsrsqtpstprrqpssqtrssttqs", "rrrtrtrrqqppptptqtprtrrrprqtrrtrppqrqpq", "ssrrsqsrqqqsrspsrrqprtppprqstqtqqtprtrrsrptqsttrp", "ptprrrsrqqtrtrpptqrprtsttppsqtpqrqsrrsprppptrqtsp", "pttqrqsqqsrqtqssqpsrppprpppsqrrprrqrrtrtprsqsrqp", "ttsqsrqsqppprpsqttsssqtqrqsstpspssppqrqqprsppprr", "ssttptsqpqrrpqtppptqrrqtppptqqrtqsrqsqspqrprrqsprp", "rqsqstspsttrppqppsrtqsqrttsrqrtrqtttrqsrqtppqrsptq", "qqqprqprtstrstrqstqtsqtsqrsptqtqsqqrprt", "prtrtstpsrtqppsrtqrqsprrppqrrqrqrqqtrqqqrsrqrprss", "ptqqtrsqrtpqrqspqtspqsqprqppssttqrrsrtqprsprpsstqt", "prqqtrsptsstrsqtqppsttspsrrrtqrsptpqrqpspppssstrp", "pqqqpttspstpssqstrtsqsrrrsrprrrsqs", "qqssqsqprqtrpsqtssqrtrrqpqsqttptptqrsrptqrspqrpr", "trrppqstrrspptptrsrtrttrptqsrtrtsqrrptpqqsrpsqqq", "qtrpsprptrtssppqtsrstssqsppqpqrtqsttppstssqssqptq", "pqqqpttsppsrtptttsrqtsptrqrrqsqsrsrpqrtrtrtpqtpr", "ppttsqqptqspqttrsptpqttqspsptrppsqstqsprtqtqrrqqt", "tsqtqqtqqrstrstqrpstttstrpptqtptpsstrtppqrsrppqt", "rqptpspprpsrqsptqtsrtsssppqpsqrppqtrtrtpqpqrppqpr", "rtttsptptqtqrspttpqsrppprptqqtsqspsttprprpqrqsqrrp", "pqqqpttspstpssrttsspsrrrpqrtpprpqr", "rqqprspqstqrqqrqptpspptqsststttsqrpssrtrrqq", "rqptpspprpsrqsptqtsrtsssppqpsqrppqtrtrtpqpsqr"}));
    ExampleRunner.eq(61, 12, new UndoHistory().minPresses(new String[]{"abcde", "a", "abcde"}));
    ExampleRunner.eq(62, 13, new UndoHistory().minPresses(new String[]{"ba", "a", "a", "b", "ba"}));
    ExampleRunner.eq(63, 12, new UndoHistory().minPresses(new String[]{"aaaaa", "a", "aaaaa"}));
    ExampleRunner.eq(64, 19, new UndoHistory().minPresses(new String[]{"abcdef", "b", "a", "ab", "abcdef"}));
    ExampleRunner.eq(65, 18, new UndoHistory().minPresses(new String[]{"abcdef", "ab", "abcde", "ab", "abc"}));
    ExampleRunner.eq(66, 30, new UndoHistory().minPresses(new String[]{"tomorrow", "topcoder", "tomorrow", "topcoder", "tomorr", "topcod"}));
    ExampleRunner.eq(67, 10, new UndoHistory().minPresses(new String[]{"abcabc", "abcab"}));
    ExampleRunner.eq(68, 11, new UndoHistory().minPresses(new String[]{"abcd", "a", "abcd"}));
    ExampleRunner.eq(69, 14, new UndoHistory().minPresses(new String[]{"abcdef", "a", "abcdeh"}));
    ExampleRunner.eq(70, 18, new UndoHistory().minPresses(new String[]{"abacus", "aba", "abacus", "aba", "abac"}));
    ExampleRunner.eq(71, 14, new UndoHistory().minPresses(new String[]{"abcd", "a", "abcdefg"}));
    ExampleRunner.eq(72, 14, new UndoHistory().minPresses(new String[]{"abcdefg", "abc", "abcdefg"}));
    ExampleRunner.eq(73, 16, new UndoHistory().minPresses(new String[]{"aaaaaaa", "a", "aaaaaaaaa"}));
    ExampleRunner.eq(74, 15, new UndoHistory().minPresses(new String[]{"aaaabbbb", "aaaa", "aaaabbbb"}));
    ExampleRunner.eq(75, 24, new UndoHistory().minPresses(new String[]{"abc", "bcdefghi", "abcdefghi"}));
    ExampleRunner.eq(76, 26, new UndoHistory().minPresses(new String[]{"abcdefg", "a", "abcdefg", "a", "abcdefg", "a", "abcdefg"}));
    ExampleRunner.eq(77, 13, new UndoHistory().minPresses(new String[]{"abcdef", "a", "abcdef"}));
    ExampleRunner.eq(78, 11, new UndoHistory().minPresses(new String[]{"aaaa", "a", "aaaa"}));
    ExampleRunner.eq(79, 15, new UndoHistory().minPresses(new String[]{"abcdefgh", "a", "abcdefgh"}));
    ExampleRunner.eq(80, 26, new UndoHistory().minPresses(new String[]{"yrmopxio", "wyrjwropn", "sf"}));
    ExampleRunner.eq(81, 13, new UndoHistory().minPresses(new String[]{"aaaaa", "a", "aaaaaa"}));
    ExampleRunner.eq(82, 17, new UndoHistory().minPresses(new String[]{"aaaaaaaaaa", "aa", "aaaaaaaaaa"}));
    ExampleRunner.eq(83, 94, new UndoHistory().minPresses(new String[]{"aaaaaaaa", "aa", "aaaaaa", "aaaaaaa", "aaa", "aaaaaabcd", "aaaaaaa", "aaaaaaaab", "aaaaaaaab", "aaaaaaaab", "aaaaaabcc", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaabbcc", "aaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaabbcdddd"}));
    ExampleRunner.eq(84, 16, new UndoHistory().minPresses(new String[]{"abacabad", "ab", "abacabada"}));
    ExampleRunner.eq(85, 15, new UndoHistory().minPresses(new String[]{"a", "abcde", "ac", "abcdef"}));
    ExampleRunner.eq(86, 2619, new UndoHistory().minPresses(new String[]{"symrohntuzdjwwojfsnojbslafadlsrdqfwemkahjdsicgrhbe", "ykiqxivyliselljjpvtpefvxnzfgggkgsuwqctqpbktoveylat", "cgyzfnylthtgpmamefhwujgqzeuzrwtvdrvkhvvaepgudjijop", "hkanaarxzktugymbjvygvfvebanjlbyslbgobznckixshltsgt", "abyyhzyukkxlclmkbnmorywoqfblzhgalfysgyptimenzqzafn", "owllndqoqqyxsjeqbmosfzfjmgbnhgbvfoiusbkktihlrlbvar", "pfqurcbsskbtfihqebromkzvxqjynjpdoizfkcaembxulhmpid", "fwpesmxbmmkdpalriyvicklaeyhsnrvuomziywjmivpavbtfzo", "pbyadeamypetkuhjchhltrijtfkmlldaoddskdeitkefelqgtx", "toqbxmjjyuwdwljzdtfhdyujfyvvhquagkeeynpzjmcfxnfcgk", "lmkfvresmlkgnrstxrgoqrauxziedqqpecwctauhnhndahwxaf", "nswqpvpxbvptkuvgwqjsxybmbbuaawfopdeezvdcqswcorlmkw", "fhuguykqykmdadggjhcmkuhixvbkilgptaxpyhfwutbuzidirf", "xdzelybnilyoatryiphpoblpykzbutirwjxikzvskvjnpanzrw", "rhycxyoybirlcouzweatzloiafkpfdlwllakjoimyaxaquaoaa", "hznxjpdvekzqgkbgunwezuezvutxitzrvnpecuajebzmlauhnq", "lpksohojexeeqztfexbggfhftuinbxdooqgcxvneusiktdsxav", "fhboowiyklynamdipdfehzyrmsugrubxdelubwulhsajfguwjz", "asbzjprdvizyhffvzgrvtaovktbgpmfreiqnxjsuuuvbzawagn", "vbolwaeagtmnntydivpdsjxpmypjyxyvyohwqlwyhlmugkzohq", "rbzoqmmfxmexkeorbgezfnmtjsflhobaqbripdqosunczdvckb", "brrqmairnrfpsxsjgjoyxismmrshvclxvcphexysrfhlfzunkk", "ljvdvhxnrurcrmgivkgvczdlkimgvwsifnnbvmqmhkqawwjugr", "plqswcajixfahnqvolhgzqqprpnajttaejtdnvovvtxcgnxwah", "fzxvqqmdqvzlyfwrijmwejsematjxusevsbmiorzlqmjwjagsp", "fzyxdmxwywqqcoiearstsdkepinpoigvhhsktsitqbktpuxrnp", "kfuwmjebbvjjqqslcodnhtqrofolybcijxfxilyjgitzalkfzn", "ujikcxrqkpunzdmgausagakbzlolsoymzjybipssgmhfrvmtqg", "twiezirnvjdwxcfvepmwjskrxdmlwetpccvbmmphvsduxkrbzd", "zjxjcxoqikvebxgxbujsbhmfbjrvkralcyuevkufupjwprvsle", "kpnywrinmuemggmcmhnhpjyyhpschfjtuwuqncebykqetcjfky", "ozhnzpertmxchtbbkqfoseyiktktzwrnvbcxshqlvpqejrgthn", "jbtjjedwzesttquwnmfdzcvpgeiozqckrvtdbyzbcrwwhsuwgz", "cfbxxhdfwexaopxhuzgtckkagusaqazufcrekwkiahkqyhysig", "lksymzuebmedhmfaqrzcbzmlsmvqfdysqsscrojvbpykbdmuxl", "yynmmfzjxgoxagptljjuekjcwnhljgwjflwtsvepdsodzewkpg", "gtsrxrgecplabsoxnguryzjmcksbwhjcaduzucgyutbvlpuaxo", "rvncirnasjkbomfkmbmscgldbyuvyrlrnatxsizmujoiwvskyg", "canpfqnzmnrzegczdwieicoymmvgwumauzpaqebetudzcfyhbi", "mmmakymgekcrkwszykfcoywuxzbxgfgsrsudtijxslqckldkvi", "mkijefkfdqkllddfhyoswggolqzocxxphfannkuscfdpkixrhl", "kftsvekxvmuudbzdqopkgurjjcugtbtfgnxdthaowukzxkdnau", "yhorsytogppauxpubidbzzwjzvvejwyjfnaznuotjftfdibgtf", "juehffddlmbkvgzxhmrxhcdbiillogqzaxhiemlqamaxububnm", "zuqexamlmcrcbubkcgypwybyvxzqaoebkufkvrvjvolzkpjovk", "dtigredswegafqwlatexccmqbwfmlcwqvfxolaghgmjmehzfdd", "ehfqxipevcirufyrtjubsapbmullborfvyythpzetkxnpwflhz", "mazcdoyozzcsgytgtcvugoefcwdjhlktnjxsxvhzwltdlmjgqf", "dwvjezfhkmuuijefcddjezwackmoqdvtbqfhskpczjxhtdoxir", "inreptodhhieckvhrpsirtuoaptomcgurxagsrjcysgaedkxse"}));
    ExampleRunner.eq(87, 39, new UndoHistory().minPresses(new String[]{"pyramid", "sphinx", "sphere", "python", "serpent"}));
    ExampleRunner.eq(88, 865, new UndoHistory().minPresses(new String[]{"pppppppppoooooooiiiiiii", "ppp", "p", "pp", "cult", "diffi", "difficul", "ljk", "kjlkjllkjljk", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bababababababababababababababa", "tootootootootootootootootooootoooo", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bababababababababababa", "dzbbzddzbbzdabcdzbbzddzbbzdabcdzbbzddzbbzdabc", "asdfasdfasdfasdfasdfjkllkjjkllkjlkjjkl", "challengingisfunchallengingisfunchallengingisfun", "testtesttesttestingtestingtesting", "testingtestingtesttestingtesttesting", "testtesttesttestingtesting", "aaaaaaaaaa", "asdfasfaskljklfjadksljfkldasjfklas", "zzzzzbbbbbbbiiiilkljkaljfsfdas", "veryveryveryhardhardhard", "difficultasdfdifficultlakjfa", "btestingtestingtesttestingtesttesting", "testtesttesttestingtesting", "aaaaaaaaaatestingtestingit", "asdfasfaskljklfjadksljfkldasjfklas", "zzzzzbbbbbbbiiiilkljkaljfsfdas", "pppcototoveryveryveryhardhardhard", "difficultasdfdifficultlakjfa", "teaestingtestingtesttestingtesttesting", "testtesttesttestingtestinginging", "aaaaaxaaaaaaaaaaaaaaaaa", "asdfasfaskljklfjadksljfkldasjfklas", "zzzzzbbbbbbbiiiilkljkaljfsfdas", "veryveryveryhardhardhard", "notnottoodifficultasdfdifficultlakjfa", "aklsdjfkjldfjasl", "yzyzdzbdzb", "dadafdfafdsaklfjadsklj", "xyzyzxpppppcotototototot", "pppppcocotocotocccctotototopcotopppppcccoootototot"}));
    ExampleRunner.eq(89, 19, new UndoHistory().minPresses(new String[]{"abcdefghijkl", "abc", "abcdefghijkl"}));
    ExampleRunner.eq(90, 21, new UndoHistory().minPresses(new String[]{"abcdefghijk", "a", "abcdefghijklmn"}));
    ExampleRunner.eq(91, 2424, new UndoHistory().minPresses(new String[]{"ab", "abcdef", "ab", "abcdef", "lrfkqyuqfjkxyqvnrtysfrzrmzlygfveulqfpdbhlqdqrrcrwd", "nxeuoqqeklaitgdphcspijthbsfyfvladzpbfudkklrwqaozmi", "xrpifeffeclhbvfukbyeqfqojwtwosileeztxwjlkngbqqmbxq", "cqptkhhqrqdwfcayssyoqcjomwufbdfxudzhiftakczvhsyblo", "etswcrfhpxprbsshsjxdfilebxwbctoayaxzfbjbkrxirimqpz", "wmshlpjhtazhbuxhwadlptoyeziwkmgsovqzgdixrpddzplcrw", "nqwqecyjyibfjykmjfqwltvzkqtpvolphckcyufdqmlglimklf", "zktgygdttnhcvpfdfbrpzlkvshwywshtdgmbqbkkxcvgumonmw", "vytbytnuqhmfjaqtgngcwkuzyamnerphfmwevhwlezohyeehbr", "cewjxvceziftiqtntfsrptugtiznorvonzjfeacgamayapwlmb", "zitzszhzkosvnknberbltlkggdgpljfisyltmmfvhybljvkypc", "flsaqevcijcyrgmqirzniaxakholawoydvchveigttxwpukzjf", "hxbrtspfttotafsngqvoijxuvqbztvaalsehzxbshnrvbykjql", "rzzfmlvyoshiktodnsjjpqplciklzqrxloqxrudygjtyzleizm", "eainxslwhhjwslqendjvxjyghrveuvphknqtsdtwxcktmwwwsd", "thzmlmbhjkmouhpbqurqfxgqlojmwsomowsjvpvhznbsilhhdk", "bdxqgrgedpzchrgefeukmcowoeznwhpiiduxdnnlbnmyjyssbs", "ococdzcuunkrfduvouaghhcyvmlkzaajpfpyljtyjjpyntsefx", "iswjutenuycpbcnmhfuqmmidmvknyxmywegmtunodvuzygvgux", "trdsdfzfssmeluodjgdgzfmrazvndtaurdkugsbdpawxitivdu", "bbqeonycaegxfjkklrfkraoheucsvpiteqrswgkaaaohxxzhqj", "tkqaqhkwberbpmglbjipnujywogwczlkyrdejaqufowbigrsnj", "niegvdvotugocedktcbbufnxorixibbdfrzuqsyrfqghoyqevc", "uanuujszitaoaowsxyglafbwzddoznrvjqeyqignpitruijvyl", "lsibobjltusrypanvybsfrxtlfmpdidtyozoolzslgdgowijat", "klvjzscizrkupmsoxftumyxifyunxucubvkfctkqlroqgzjvjw", "zizppvsomflvioemycnphfjtbnwedtubynsbirepgcxfgsfomh", "vpmymkdohettyycsibbeaxniwjkfvabnrllkmaglythkglauzg", "keulyrpaeurdvexqlwgakdtbihmfrjijanxkhrqdllecyhbsux", "nlftmjcnyybwsjmajbwtuhkkiovytgaufpjlxiwbnzhybsxfmu", "mbhkjqmdabmyulbrglwstjkoxbczkjhvhsgzvwiixxaobhfsop", "qnebmflcooetjizolqrmsxphqdgzdmqhoggvrvjqrpmxbhkkfg", "zzxjegsyovdrmwcjavpmshojzxaxnbiztkfomzdhujdmcyxdqt", "eqjalgqgsomonvbreqqzzpwqlihdnvudvlznfhbaokxvcelykf", "hxbldylqqewdnjzrlbskqgfvnqlfvobeyolyyovviwhxfpbuiu", "jlolnjldgvwxljboaypaotdzjxxrschmwrveliumzpnoieipog", "wilaswntywuegdgyethsrznlzrffmwdgxaigmxpyvyaqgaulto", "dtlgzcyvfiykmkllfbzxqyhvizqmamjzlvvgoifltzywueypma", "binmyappzaecvmxirqsmzcuiddymnlfuskiheknevxtehxtbth", "qkjvtfzddlgchxczohpyewfmufzazyxtqxcuwbrxpfymuvfvsy", "xrrcfuusicczaqhlswbzievijhrvdudvmaravupityzffecdks", "uxteeitxtgwdfuydrtbfypbnkcypqodxrrwikfuxwjhtujrliu", "aifppzvkmxyspwvpfyfpkvgthqqrmajxispjncxgviyuqavayv", "svznmhskodmidajwlkfrimprrhenguipdghstyopbvuiqcoplv", "wduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasi", "nwspsqiukflhyfacamqrbqrypstsxhplrrmbeddvphnegtuxxt"}));
    ExampleRunner.eq(92, 3, new UndoHistory().minPresses(new String[]{"a", "a"}));
    ExampleRunner.eq(93, 18, new UndoHistory().minPresses(new String[]{"abcdefghijk", "a", "abcdefghij"}));
    ExampleRunner.eq(94, 13, new UndoHistory().minPresses(new String[]{"bcdefg", "b", "bcdefg"}));
    ExampleRunner.eq(95, 14, new UndoHistory().minPresses(new String[]{"abcde", "a", "abcdefg"}));
    ExampleRunner.eq(96, 12, new UndoHistory().minPresses(new String[]{"ababa", "a", "ababa"}));
    ExampleRunner.eq(97, 18, new UndoHistory().minPresses(new String[]{"aaaaaa", "a", "aaaaaaaaaaa"}));
    ExampleRunner.eq(98, 9, new UndoHistory().minPresses(new String[]{"do", "d", "dog"}));
    ExampleRunner.eq(99, 14, new UndoHistory().minPresses(new String[]{"abcdefg", "a", "abcdefg"}));
    ExampleRunner.eq(100, 12, new UndoHistory().minPresses(new String[]{"abcde", "ab", "abcde"}));
    ExampleRunner.eq(101, 13, new UndoHistory().minPresses(new String[]{"today", "to", "todays"}));
    ExampleRunner.eq(102, 13, new UndoHistory().minPresses(new String[]{"abcde", "a", "abcdef"}));
    ExampleRunner.eq(103, 38, new UndoHistory().minPresses(new String[]{"aaaaaaaaaaaaaaaaaaaa", "a", "aaaaaaaaaaaaaaaaaaaaaa", "aaaaaaa", "aaaaaaaaaa", "aaaaaaaaaaaaa"}));
    ExampleRunner.eq(104, 20, new UndoHistory().minPresses(new String[]{"abcd", "bc", "a", "abcdefgh"}));
    ExampleRunner.eq(105, 19, new UndoHistory().minPresses(new String[]{"aaaaaaaaaa", "a", "aaaaaaaaaaaa"}));
    ExampleRunner.eq(106, 14, new UndoHistory().minPresses(new String[]{"a", "aaaaaa", "a", "aaaaaa"}));
    ExampleRunner.eq(107, 12, new UndoHistory().minPresses(new String[]{"aca", "cacac"}));
    ExampleRunner.eq(108, 15, new UndoHistory().minPresses(new String[]{"abcdefgh", "abcd", "abcdefg"}));
    ExampleRunner.eq(109, 4, new UndoHistory().minPresses(new String[]{"a", "ap"}));
    ExampleRunner.eq(110, 11, new UndoHistory().minPresses(new String[]{"abcd", "ab", "abce"}));
    ExampleRunner.eq(111, 12, new UndoHistory().minPresses(new String[]{"abaaa", "a", "abaaa"}));
    ExampleRunner.eq(112, 13, new UndoHistory().minPresses(new String[]{"abacus", "a", "abacus"}));
    ExampleRunner.eq(113, 13, new UndoHistory().minPresses(new String[]{"aaaaaa", "a", "aaaaa"}));
    ExampleRunner.eq(114, 18, new UndoHistory().minPresses(new String[]{"abcdef", "a", "ab", "abc", "abcdefg"}));
    ExampleRunner.eq(115, 18, new UndoHistory().minPresses(new String[]{"aaaaaaaaaa", "a", "aaaaaaaaaaa"}));
    ExampleRunner.eq(116, 22, new UndoHistory().minPresses(new String[]{"too", "tooo", "toooo", "tooootoo", "s", "stoooo"}));
    ExampleRunner.eq(117, 14, new UndoHistory().minPresses(new String[]{"abcdefg", "ab", "abcdefg"}));
    ExampleRunner.eq(118, 10, new UndoHistory().minPresses(new String[]{"ab", "cabd"}));
    ExampleRunner.eq(119, 14, new UndoHistory().minPresses(new String[]{"abcdefg", "ab", "abcdef"}));
    ExampleRunner.eq(120, 15, new UndoHistory().minPresses(new String[]{"topco", "to", "topcoder"}));
    ExampleRunner.eq(121, 6, new UndoHistory().minPresses(new String[]{"a", "b"}));
    ExampleRunner.eq(122, 12, new UndoHistory().minPresses(new String[]{"abcde", "a", "abcd"}));
    ExampleRunner.eq(123, 11, new UndoHistory().minPresses(new String[]{"xyzt", "x", "xyzt"}));
    ExampleRunner.eq(124, 14, new UndoHistory().minPresses(new String[]{"abcdef", "ab", "abcdefg"}));
    ExampleRunner.eq(125, 148, new UndoHistory().minPresses(new String[]{"tomorrow", "topcoder", "abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstuvwxyzabcdefghijk", "abcdefghijklmnopqrstuvwxyzabcdef", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv", "xyz", "aiueokakikukekosasisuseso", "aiueokakiku", "aiueokakiku", "aiueokakiku", "aiueokakiku", "a", "a", "a", "m", "m", "m", "aiueokakikukeko", "aiueoka", "aiueokakikukeko", "aiueo", "aiueo", "aiueokakikukekosasisuseso", "abcdefghijkomn"}));
    ExampleRunner.eq(126, 20, new UndoHistory().minPresses(new String[]{"aaaaaaaaaaaaa", "a", "aaaaaaaaaaaaa"}));
    ExampleRunner.eq(127, 14, new UndoHistory().minPresses(new String[]{"abcdef", "a", "abcdefg"}));
    ExampleRunner.eq(128, 17, new UndoHistory().minPresses(new String[]{"abcdefghij", "abc", "abcdefghij"}));
    ExampleRunner.eq(129, 22, new UndoHistory().minPresses(new String[]{"abcde", "a", "abcdef", "a", "a", "a", "a", "a", "a", "a"}));
    ExampleRunner.eq(130, 12, new UndoHistory().minPresses(new String[]{"bacd", "a", "bacd"}));
    ExampleRunner.eq(131, 101, new UndoHistory().minPresses(new String[]{"abcd", "abcdefgh", "efghabc", "cdefgh", "abcdabcdabcd", "ghabcef", "abcef", "abcdabcdabcdfttttt", "ttttt", "tt", "ab", "abcd", "abcf", "abd", "abe", "hifeg"}));
    ExampleRunner.eq(132, 21, new UndoHistory().minPresses(new String[]{"topcoder", "t", "topcoder", "t", "topcoder"}));
    ExampleRunner.eq(133, 9, new UndoHistory().minPresses(new String[]{"abc", "adc"}));
    ExampleRunner.eq(134, 12, new UndoHistory().minPresses(new String[]{"abb", "cd", "abb"}));
    ExampleRunner.eq(135, 16, new UndoHistory().minPresses(new String[]{"abcdefghi", "abc", "abcdefgh"}));
    ExampleRunner.eq(136, 25, new UndoHistory().minPresses(new String[]{"orz", "zro", "osz", "zso", "otz"}));
    ExampleRunner.eq(137, 42, new UndoHistory().minPresses(new String[]{"c", "c", "a", "a", "a", "c", "c", "ba", "bac", "baf", "a", "c", "bat", "bar", "barc", "barcn"}));
    ExampleRunner.eq(138, 16, new UndoHistory().minPresses(new String[]{"abcdefghi", "a", "abcdefgh"}));
    ExampleRunner.eq(139, 80, new UndoHistory().minPresses(new String[]{"a", "ab", "abac", "abacus", "pyramid", "sphinx", "sphere", "python", "serpent", "abacus", "abacfs", "ab", "a", "serpent", "python", "sphere", "sphinx", "pyramid"}));
    ExampleRunner.eq(140, 20, new UndoHistory().minPresses(new String[]{"abc", "abcdefghij", "abc", "abcdefghijkl"}));
    ExampleRunner.eq(141, 15, new UndoHistory().minPresses(new String[]{"abcdefg", "ab", "abcdef", "abcdef"}));
    ExampleRunner.eq(142, 9, new UndoHistory().minPresses(new String[]{"aaaa", "aaaaaaa"}));
    ExampleRunner.eq(143, 4, new UndoHistory().minPresses(new String[]{"a", "ab"}));
    ExampleRunner.eq(144, 17, new UndoHistory().minPresses(new String[]{"aaaaa", "a", "aaaaaaaaaa"}));
    ExampleRunner.eq(145, 16, new UndoHistory().minPresses(new String[]{"bcdefg", "bbcdefg"}));
    ExampleRunner.eq(146, 17, new UndoHistory().minPresses(new String[]{"aaaaaaaaaa", "a", "aaaaaaaaaa"}));
    ExampleRunner.eq(147, 52, new UndoHistory().minPresses(new String[]{"ba", "a", "a", "b", "ba", "ba", "b", "a", "a", "ba", "a", "ba", "a", "a", "a", "a", "a", "a", "ba", "ba", "ba", "a", "a", "b", "ba"}));
    ExampleRunner.eq(148, 37, new UndoHistory().minPresses(new String[]{"ttttttttttttttttttt", "t", "tttttttttttttttttttttttttttttt"}));
    ExampleRunner.eq(149, 21, new UndoHistory().minPresses(new String[]{"topcoder", "atopcoder"}));
    ExampleRunner.eq(150, 17, new UndoHistory().minPresses(new String[]{"aaaaaaa", "a", "aaaaaaaaaa"}));
    ExampleRunner.eq(151, 10, new UndoHistory().minPresses(new String[]{"abc", "ab", "abcd"}));
    ExampleRunner.eq(152, 91, new UndoHistory().minPresses(new String[]{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "a", "aaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}));
    ExampleRunner.eq(153, 62, new UndoHistory().minPresses(new String[]{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}));
    ExampleRunner.eq(154, 21, new UndoHistory().minPresses(new String[]{"batase", "a", "b", "batasewert"}));
    ExampleRunner.eq(155, 198, new UndoHistory().minPresses(new String[]{"abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a", "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy", "a"}));
    ExampleRunner.eq(156, 15, new UndoHistory().minPresses(new String[]{"abcdefrt", "a", "abcdefrt"}));
    ExampleRunner.eq(157, 16, new UndoHistory().minPresses(new String[]{"a", "bbbbb", "b", "bbbbb"}));
    ExampleRunner.eq(158, 100, new UndoHistory().minPresses(new String[]{"ab", "a", "abcdefgh", "abharhg", "abafsbiafhb", "aetobeagnea", "afbhadkbgfdka", "hdbjbhdjb", "djbhrudubhdu", "fbdjbvdj"}));
    ExampleRunner.eq(159, 12, new UndoHistory().minPresses(new String[]{"abcd", "a", "abcde"}));
    ExampleRunner.eq(160, 1290, new UndoHistory().minPresses(new String[]{"tomorrow", "topcoder", "abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstuvwxyzabcdefghijk", "abcdefghijklmnopqrstuvwxyzabcdef", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv", "xyz", "aiueokakikukekosasisuseso", "aiueokakiku", "aiueokakiku", "aiueokakiku", "aiueokakiku", "a", "a", "a", "m", "m", "m", "aiueokakikukeko", "aiueoka", "aiueokakikukeko", "aiueo", "aiueo", "aiueokakikukekosasisuseso", "abcdefghijkomn", "kokokaradokokamadeittemiyoukanaatoomounndakedo", "kokokaradokafodsafoiasjdgoiajsdfjsdfjasoidfjasoifj", "aisdfjhaspghkjrehgjkewahjkfasdhkfjhasdjkfhasdlf", "aksdhfkjashdgiuhweufhsakjfhjkasdhfjahljkgfafjkasdf", "ifidhbfdjksfhsaljhdfkjladhsfjkdsahkfjhsdkjfasd", "hiasdhgiuwaheiufhuahfkjashjkfhasjkdghakjehfjwa", "lkjeahrlkgjhaskfhkajslhdfkjasdkjfhaskdjlfhkjasdhfk", "kashekfljhasjkhfakjwenfjkwebnjkfbnewjkbfjka", "kljawehgipuasdhgiuaekwheajflksafndsafdsfd", "aiuhpgaiwehjfoajwkelfjhkwahefjkalhdjkfhsdfasdf", "pasidhiadpsbjiajeiofjaiojhfkashdfsahdjkfahsdkjfh", "aiueokakikukekosasisusesotatitutetonaninuneo", "abcdefghjikoajeopifgjasdklfjasdlkfjkalsdfj", "askdfjksajdhfkjasdhfkjlhasdjkfhasdkjfhlkasjfhsad", "lasdkjhfkalsjdhfkjashdfkjlahsdjkfhaskjdlfhjaksdf", "lasdkjhflakshgjwhegipusahfglasdkhfgkjasdhf", "halsdhfjiaweihfuhawfhaskjljfhkjsdahfjkasdhfkjla", "klasdhfkjlasjhdfkljhwejlkghjklghadlskjhfjkaslhfas", "lasjkdhflkasjhgiauehfioauhfsakjfhaksjdhfkjasd", "haisdhgioaweuhfkawjehfkjasdhfklahsdjkflasd", "ibaeuhboiaeuhrgkajhdfkljashdfjkashdljfaskdfas", "hipbueahiobuhafhaklsjhfaskdjfhjasdkfsadjfha", "hlasijhefkjahkflahsjdfhalwkehfksahdjfalskdjhfa", "laskdhfakljehfipuwhefiouashfklasdjhfjkashdjfa", "liashgfoiasuhfashdfjkashdfkjlashdfkjlasdhfksdf"}));
    ExampleRunner.eq(161, 168, new UndoHistory().minPresses(new String[]{"babbb", "bbb", "aa", "aaa", "aba", "a", "b", "aa", "baa", "babba", "aabaa", "baaa", "aabaa", "b", "b", "bb", "abaa", "b", "abb", "abaaa", "abbb", "a", "a", "aa", "bb", "baa", "ababa", "abaab", "baa", "babab", "bbba", "a", "abab", "baaab", "a", "ab", "bb", "bb", "ab", "bab", "bb", "bbaab", "aaaa", "bba", "bbbb", "aba", "aabb", "b", "b", "a"}));
    ExampleRunner.eq(162, 11, new UndoHistory().minPresses(new String[]{"abcd", "a", "abc"}));
    ExampleRunner.eq(163, 22, new UndoHistory().minPresses(new String[]{"a", "ins", "remains", "s"}));
    ExampleRunner.eq(164, 19, new UndoHistory().minPresses(new String[]{"abcabcabcabc", "abc", "abcabcabcabc"}));
    ExampleRunner.eq(165, 12, new UndoHistory().minPresses(new String[]{"aaaa", "a", "aaaab"}));
    ExampleRunner.eq(166, 18, new UndoHistory().minPresses(new String[]{"baqdef", "a", "a", "b", "baqdef"}));
    ExampleRunner.eq(167, 13, new UndoHistory().minPresses(new String[]{"aaaaaa", "a", "aaaaaa"}));
    ExampleRunner.eq(168, 16, new UndoHistory().minPresses(new String[]{"aaaaa", "a", "aaaaaaaaa"}));
    ExampleRunner.eq(169, 21, new UndoHistory().minPresses(new String[]{"aaaaaaaa", "a", "aaaaaaaaaaaaaa"}));
    ExampleRunner.eq(170, 15, new UndoHistory().minPresses(new String[]{"topcoder", "top", "topcoder"}));
    ExampleRunner.eq(171, 98, new UndoHistory().minPresses(new String[]{"abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxabcdefghijklmnopqrstuvwx"}));
    ExampleRunner.eq(172, 12, new UndoHistory().minPresses(new String[]{"aaaaa", "a", "aaaa"}));
    ExampleRunner.eq(173, 101, new UndoHistory().minPresses(new String[]{"abcdef", "a", "abcdefgh", "abharhg", "abafsbiafhb", "aetobeagnea", "afbhadkbgfdka", "hdbjbhdjb", "djbhrudubhdu", "fbdjbvdj"}));
    ExampleRunner.eq(174, 6, new UndoHistory().minPresses(new String[]{"abc", "abcd"}));
    ExampleRunner.eq(175, 39, new UndoHistory().minPresses(new String[]{"aaaaaaaaaaaaaabbbaaa", "asdaa", "da", "aa", "aaaaaaaaaaaaaa"}));
    ExampleRunner.eq(176, 27, new UndoHistory().minPresses(new String[]{"topcoder", "smalex", "topcodersmalex"}));
    ExampleRunner.eq(177, 13, new UndoHistory().minPresses(new String[]{"a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"}));
    ExampleRunner.eq(178, 38, new UndoHistory().minPresses(new String[]{"a", "ba", "aaa", "baaa", "aba", "baa", "baack", "aloha", "ba"}));
    ExampleRunner.eq(179, 155, new UndoHistory().minPresses(new String[]{"abcd", "abcdefgh", "efghabc", "cdefgh", "abcdabcdabcd", "ghabcef", "abcef", "abcdabcdabcdfttttt", "ttttt", "tt", "ab", "abcd", "abcf", "abd", "abe", "hifeg", "asdfghjkl", "asdfghjkl", "a", "s", "d", "f", "jkhgf", "qerty", "ghdfh", "abcfgh"}));
    ExampleRunner.eq(180, 67, new UndoHistory().minPresses(new String[]{"aaaaaa", "a", "aaaaaaaaaaa", "aaaaaaaaaaaa", "aaaaaaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaaaaaaaaaaaaaaaa", "bbb", "aaa", "bb", "aaaaaa", "bbbbbbbbbbbbb"}));
    ExampleRunner.eq(181, 20, new UndoHistory().minPresses(new String[]{"abcdefghijk", "a", "abcdefghijklm"}));
    ExampleRunner.eq(182, 23, new UndoHistory().minPresses(new String[]{"aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaa"}));
    ExampleRunner.eq(183, 18, new UndoHistory().minPresses(new String[]{"a", "ab", "abac", "abacus", "aba", "abacuses"}));
    ExampleRunner.eq(184, 9, new UndoHistory().minPresses(new String[]{"ab", "a", "abc"}));
    ExampleRunner.eq(185, 8, new UndoHistory().minPresses(new String[]{"abcx", "abc"}));
    ExampleRunner.eq(186, 8, new UndoHistory().minPresses(new String[]{"hossam", "hossam"}));
    ExampleRunner.eq(187, 94, new UndoHistory().minPresses(new String[]{"asdfasdfasdfasdfasdfadsf", "asdfasdfasdfasdadsfsadfsda", "asdfasdfasdfasdf", "a", "asd", "asdf", "asdfasdfasdfasdfasdfasdf", "asdfasdfasdfasdfasdfasdf", "asdfasdfasdfasdfasdfasdfasdf", "aaaaassss", "asdfvvbbccmmklopiuytrd"}));
    ExampleRunner.eq(188, 15, new UndoHistory().minPresses(new String[]{"abcdef", "abc", "abce", "abcd"}));
    ExampleRunner.eq(189, 23, new UndoHistory().minPresses(new String[]{"aaaaaaaaaaaaaaa", "b", "aaaaaaaaaaaaaaa"}));
    ExampleRunner.eq(190, 141, new UndoHistory().minPresses(new String[]{"ddddddddddddddddddddddd", "ddddddddddd", "dddddddddddd", "ddddddddddddddddddddddddddddd", "ddddddddddddddd", "ddddddddddddddddddddddddddd", "ddddddddddddddddddddddddd", "dddddddddddddddddddddddddddddddddddddddddddddddd", "ddddddddddddddddddddddddddd", "dddddddddd", "ddddddddddddddddddddddddddddddddddddd", "dddddddddddddddddddddddddddddd", "dddddddddddddd", "ddd", "dddddddddddddd", "ddddddddddddddddddddddddddddddddddddd", "dddddddddddddddddddddddddddddddddddddddddd", "dddddddddddddddd", "ddddddddddddddddddd", "ddddddddddddddddddddddddddd", "ddddddddddddddddddddddddd", "dddddddddddd", "ddddddddddddddddddddd", "dddddddddddddddddddddddd", "dddddddddddddddddddddddddddddddddddddddddd", "dddd", "ddddddddddddddddddddddddddddddddddddddddddd", "dddddddddddddddddddddddddddddddddddddddddddddd", "dddddd", "dddddddd", "dddddddddddddddddddddddddddddddddddddddddddd", "ddddddddddddddddddddddddddddddddddddddddddddddd"}));
    ExampleRunner.eq(191, 14, new UndoHistory().minPresses(new String[]{"aab", "a", "aaaa", "aaa"}));
    ExampleRunner.eq(192, 1169, new UndoHistory().minPresses(new String[]{"ajkshfkjahsdfkhakfhakjdshfkajshfiwehifuahwkfuahskf", "aalsdjfaskdjflkajsdlfjalsdfjlasdjfklajdsklfjajlkds", "aasdjfksajdkfjalsdjfkhkasdhfkhaskdhfkahsdhfkasdfha", "kjahdfkjahsdjkfhjkasdhfjkahsdkhfkjahsdjkfhjkasdhhb", "bankkajsfkjsadkfjksljdkfajshdjkfhasdkjfhjkasdhfkjs", "alsflkjsdlkfjlkasjdflkjaslkdjflkasjdflajdslfjalsdj", "aksjdfkashdkfhakdsjhfjkasdhkfjahsdjkfhaksdhfkhasdf", "asjfdkhaskdjhfjklasdhflkjahdjkfhaskdjhfkajshdfkajh", "jhsadkjfhkajsdhflkashdfjkahsdkfahsdkjfhajksdhfkjad", "aksdjfkjahdskjfhadskjhfajkdshfkjahsdjkfhajksdhfkja", "aahsdkfjhaskdhfuiewnkfuawhfkasdhfjhasdjhfkajsdhkfa", "ahskjfdhaksjhdfkaskdhfjkhadskjfhajksdhfjkhadsjkfhj", "alshfkahsjdhfjkasdhfkjhasdjkhfjkahsdkjfhkajshdfjkh", "sdhkfjhauewhfuiewhfjkashdfjahsdjkfhajksdhfkjasdhhf", "sjdkjfhajksdhfjkahdsfjkhasjkdfhjkasdhfkjashdkjfhas", "akjshdfjkashdflkjahsdkjfhajksdhfkjashdfsajdhfklajs", "hfakjshdfjkahsdkfjhaksjdhfalsdkhfalkjsdhflaksjdhfa", "ashdfkjahdsfjkahsdkjhfakjsdhfjkahsdruwehfjkahsdkfh", "kjashkdjfhasjkdhfajkshdfjkahsdkjfhasdjkfhaksdhfaas", "ksajhfdjkahsdkfhalsdkjfhalkjdshfkjasdhfjkashdjkfhs", "ashfdjkahsdjkfhasjdkhfjadshjfkahsdfhajksdhfjasdfhd", "ajkshfkjahsdfkhakfhakjdshfkajshfiwehifuahwkfuahskf", "aalsdjfaskdjflkajsdlfjalsdfjlasdjfklajdsklfjajlkds", "aasdjfksajdkfjalsdjfkhkasdhfkhaskdhfkahsdhfkasdfha", "kjahdfkjahsdjkfhjkasdhfjkahsdkhfkjahsdjkfhjkasdhhb", "bankkajsfkjsadkfjksljdkfajshdjkfhasdkjfhjkasdhfkjs", "alsflkjsdlkfjlkasjdflkjaslkdjflkasjdflajdslfjalsdj", "aksjdfkashdkfhakdsjhfjkasdhkfjahsdjkfhaksdhfkhasdf", "asjfdkhaskdjhfjklasdhflkjahdjkfhaskdjhfkajshdfkajh", "jhsadkjfhkajsdhflkashdfjkahsdkfahsdkjfhajksdhfkjad", "aksdjfkjahdskjfhadskjhfajkdshfkjahsdjkfhajksdhfkja", "aahsdkfjhaskdhfuiewnkfuawhfkasdhfjhasdjhfkajsdhkfa", "ahskjfdhaksjhdfkaskdhfjkhadskjfhajksdhfjkhadsjkfhj", "alshfkahsjdhfjkasdhfkjhasdjkhfjkahsdkjfhkajshdfjkh", "sdhkfjhauewhfuiewhfjkashdfjahsdjkfhajksdhfkjasdhhf", "sjdkjfhajksdhfjkahdsfjkhasjkdfhjkasdhfkjashdkjfhas", "akjshdfjkashdflkjahsdkjfhajksdhfkjashdfsajdhfklajs", "hfakjshdfjkahsdkfjhaksjdhfalsdkhfalkjsdhflaksjdhfa", "ashdfkjahdsfjkahsdkjhfakjsdhfjkahsdruwehfjkahsdkfh", "kjashkdjfhasjkdhfajkshdfjkahsdkjfhasdjkfhaksdhfaas", "ksajhfdjkahsdkfhalsdkjfhalkjdshfkjasdhfjkashdjkfhs", "ashfdjkahsdjkfhasjdkhfjadshjfkahsdfhajksdhfjasdfhd", "ashfdjkahsdjkfhasjdkhfjadshjfkahsdfhajksdhfjasdfhd", "alshfkahsjdhfjkasdhfkjhasdjkhfjkahsdkjfhkajshdfjkh", "sdhkfjhauewhfuiewhfjkashdfjahsdjkfhajksdhfkjasdhhf", "sjdkjfhajksdhfjkahdsfjkhasjkdfhjkasdhfkjashdkjfhas", "akjshdfjkashdflkjahsdkjfhajksdhfkjashdfsajdhfklajs", "hfakjshdfjkahsdkfjhaksjdhfalsdkhfalkjsdhflaksjdhfa", "ashdfkjahdsfjkahsdkjhfakjsdhfjkahsdruwehfjkahsdkfh", "kjashkdjfhasjkdhfajkshdfjkahsdkjfhasdjkfhaksdhfaas"}));
  }

  public int minPresses(String[] lines) {
    ArrayList<String> undo = new ArrayList<String>();
    undo.add("");
    int result = 0;
    String cur = "";
    for (int i = 0; i < lines.length; i++) {
      final String line = lines[i];
      if (i > 0) {
        // reset buffer
        result += Math.min(
            line.startsWith(cur) ? (1 + line.length() - cur.length()) : 99999,
            2 + 1 + cutString(undo, line).length());
      } else {
        result += line.length() + 1;
      }
      cur = line;
      undo.add(line);
//      System.out.println("line = " + line + " res = " + result);
    }
    return result;
  }

  private String cutString(ArrayList<String> undo, String line) {
    for (int l = line.length(); l >= 0; l--) {
      String sub = line.substring(0, l);
//      System.out.println("sub = " + sub);
      for (String str : undo) {
        if (str.startsWith(sub)) {
//          System.out.println("sub = " + sub);
//          System.out.println("line.substring(l) = " + line.substring(l));
          return line.substring(l);
        }
      }
    }
    return null;
  }

}
